"""
M14 Lab -- Multi-Agent Systems: Writer Subagent (Solution)
==========================================================
The Writer generates a formatted risk report from research
findings and analysis. No tools — purely text generation.

Usage (standalone test):
    python writer.py
"""

import json
import sys
import os
from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "starter"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import anthropic

client = anthropic.Anthropic()
MODEL = "claude-sonnet-4-20250514"


WRITER_SYSTEM_PROMPT = """You are a professional report writer specializing in UCC lien analysis.
You receive research findings and analysis from other agents, and your job is to
produce a clear, well-structured risk report.

## Report Format
Use EXACTLY this structure:

# UCC Lien Risk Report: [Entity Name]

## Executive Summary
[2-3 sentences: who the entity is, how many filings found, overall risk level]

## Filing Details
[For each filing: number, type, state, status, date, secured party, collateral summary]

## Risk Assessment
- **Risk Score**: [X.XX / 1.00]
- **Risk Level**: [LOW/MEDIUM/HIGH]
- **Key Patterns**: [list patterns identified by analyst]

## Recommendation
[Actionable recommendation based on the analysis]

---
*Report generated by Multi-Agent Pipeline | Data as of search date*

## Rules
- ONLY use data provided. Never fabricate filing numbers or details.
- Cite specific filing numbers in the Filing Details section.
- Keep the Executive Summary concise (2-3 sentences max).
- The Recommendation must be actionable and specific.
"""


def run_writer(findings_json: str, analysis_json: str) -> str:
    """
    Run the Writer subagent to generate a formatted risk report.

    No tools — single API call for text generation.

    Args:
        findings_json: JSON string from the Researcher agent
        analysis_json: JSON string from the Analyst agent

    Returns:
        Formatted report string
    """
    task = f"""Write a UCC Lien Risk Report based on the following data.

## Research Findings (from Researcher agent)
{findings_json}

## Analysis (from Analyst agent)
{analysis_json}

Generate the report now, following the exact format in your instructions."""

    print(f"\n[WRITER] Generating report...")

    response = client.messages.create(
        model=MODEL,
        max_tokens=4096,
        system=WRITER_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": task}],
    )

    text = ""
    for block in response.content:
        if hasattr(block, "text"):
            text += block.text

    print(f"[WRITER] Complete ({len(text)} chars)")
    return text


if __name__ == "__main__":
    print("=" * 60)
    print("M14 Writer — Standalone Test (SOLUTION)")
    print("=" * 60)

    sample_findings = json.dumps({
        "entity": "Greenfield Logistics LLC",
        "total_found": 1,
        "filings": [
            {
                "filing_number": "UCC-2024-NY-0012847",
                "type": "UCC-1",
                "state": "New York",
                "status": "Active",
                "filing_date": "2024-03-15",
                "secured_party": "Atlantic Capital Partners",
                "collateral_summary": "All accounts receivable, inventory, equipment...",
            }
        ],
    })

    sample_analysis = json.dumps({
        "entity": "Greenfield Logistics LLC",
        "risk_score": 0.55,
        "risk_level": "MEDIUM",
        "patterns": [
            {"pattern": "Blanket lien", "detail": "Covers all AR, inventory, equipment", "severity": "medium"}
        ],
        "summary": "Single active filing with broad collateral coverage.",
        "recommendation": "Review collateral descriptions and secured party priorities.",
    })

    result = run_writer(sample_findings, sample_analysis)
    print(f"\n[WRITER] Report:\n{result}")
