"""
Mock Pre-Authorization Records
================================
This module contains simulated pre-authorization data for the Healthcare
Pre-Auth Status Checker agent. Each record represents a prior authorization
request submitted by a provider to a payer (insurance company).

In production, this data would come from a payer's authorization management
system via an API (e.g., X12 278 transactions or a proprietary REST API).
"""

PREAUTH_RECORDS = {
    "PA-2024-00142": {
        "reference_id": "PA-2024-00142",
        "status": "approved",
        "patient_name": "Maria Gonzalez",
        "patient_dob": "1987-03-14",
        "member_id": "HMO-889421",
        "provider_npi": "1234567890",
        "provider_name": "Dr. Sarah Chen, MD — Orthopedic Surgery",
        "payer": "BlueCross BlueShield of Illinois",
        "plan_type": "HMO",
        "cpt_code": "27447",
        "cpt_description": "Total knee replacement (arthroplasty)",
        "icd10_codes": ["M17.11"],
        "icd10_descriptions": ["Primary osteoarthritis, right knee"],
        "requested_date": "2024-10-01",
        "determination_date": "2024-10-08",
        "expiration_date": "2025-01-08",
        "clinical_reviewer": "Dr. James Whitfield, MD — Utilization Review",
        "reviewer_notes": "Meets InterQual criteria for TKA. Conservative treatment (PT, NSAIDs, corticosteroid injections) documented over 6-month period with insufficient relief. BMI 28.4 within acceptable range. Approved for inpatient stay up to 3 days.",
        "facility": "Northwestern Memorial Hospital",
        "estimated_cost": 42500.00,
        "urgency": "elective",
    },
    "PA-2024-00278": {
        "reference_id": "PA-2024-00278",
        "status": "pending",
        "patient_name": "Robert Williams",
        "patient_dob": "1955-11-22",
        "member_id": "PPO-554310",
        "provider_npi": "9876543210",
        "provider_name": "Dr. Anita Patel, MD — Cardiology",
        "payer": "Aetna",
        "plan_type": "PPO",
        "cpt_code": "33533",
        "cpt_description": "Coronary artery bypass graft (CABG), single arterial graft",
        "icd10_codes": ["I25.10", "I11.9"],
        "icd10_descriptions": [
            "Atherosclerotic heart disease of native coronary artery without angina pectoris",
            "Hypertensive heart disease without heart failure",
        ],
        "requested_date": "2024-11-15",
        "determination_date": None,
        "expiration_date": None,
        "clinical_reviewer": None,
        "reviewer_notes": "Pending peer-to-peer review. Cardiac catheterization report requested. Awaiting documentation of ejection fraction and stress test results from referring cardiologist.",
        "facility": "Cleveland Clinic",
        "estimated_cost": 123000.00,
        "urgency": "urgent",
    },
    "PA-2024-00398": {
        "reference_id": "PA-2024-00398",
        "status": "denied",
        "patient_name": "James O'Brien",
        "patient_dob": "1972-06-30",
        "member_id": "EPO-112938",
        "provider_npi": "5678901234",
        "provider_name": "Dr. Michael Torres, MD — Pain Management",
        "payer": "UnitedHealthcare",
        "plan_type": "EPO",
        "cpt_code": "63030",
        "cpt_description": "Lumbar laminotomy (hemilaminectomy) with decompression",
        "icd10_codes": ["M51.16", "M54.5"],
        "icd10_descriptions": [
            "Intervertebral disc disorders with radiculopathy, lumbar region",
            "Low back pain",
        ],
        "requested_date": "2024-09-20",
        "determination_date": "2024-10-02",
        "expiration_date": None,
        "clinical_reviewer": "Dr. Linda Park, MD — Utilization Review",
        "reviewer_notes": "Denied — does not meet medical necessity criteria. Documentation shows only 4 weeks of conservative treatment (physical therapy). Plan requires minimum 6 weeks of PT and at least one epidural steroid injection before surgical intervention. Provider may resubmit after completing conservative treatment protocol. Appeal rights provided in denial letter.",
        "facility": "Johns Hopkins Hospital",
        "estimated_cost": 35800.00,
        "urgency": "elective",
    },
    "PA-2024-00415": {
        "reference_id": "PA-2024-00415",
        "status": "info-requested",
        "patient_name": "Diane Kowalski",
        "patient_dob": "1963-08-19",
        "member_id": "HMO-667234",
        "provider_npi": "3456789012",
        "provider_name": "Dr. Emily Zhang, MD — Oncology",
        "payer": "Cigna",
        "plan_type": "HMO",
        "cpt_code": "77386",
        "cpt_description": "Intensity-modulated radiation therapy (IMRT), complex",
        "icd10_codes": ["C50.911"],
        "icd10_descriptions": ["Malignant neoplasm of unspecified site of right female breast"],
        "requested_date": "2024-11-01",
        "determination_date": None,
        "expiration_date": None,
        "clinical_reviewer": "Dr. Robert Crane, MD — Oncology Review",
        "reviewer_notes": "Additional information requested: (1) Pathology report with tumor staging (TNM), (2) HER2/ER/PR receptor status results, (3) Oncotype DX recurrence score if available, (4) Multi-disciplinary tumor board recommendation. Respond within 14 calendar days to avoid administrative denial.",
        "facility": "MD Anderson Cancer Center",
        "estimated_cost": 87600.00,
        "urgency": "urgent",
    },
    "PA-2024-00523": {
        "reference_id": "PA-2024-00523",
        "status": "approved",
        "patient_name": "Anthony Mitchell",
        "patient_dob": "1990-01-07",
        "member_id": "PPO-998712",
        "provider_npi": "2345678901",
        "provider_name": "Dr. Rachel Hoffman, MD — Gastroenterology",
        "payer": "BlueCross BlueShield of Texas",
        "plan_type": "PPO",
        "cpt_code": "43239",
        "cpt_description": "Upper GI endoscopy with biopsy",
        "icd10_codes": ["K21.0", "K44.9"],
        "icd10_descriptions": [
            "Gastro-esophageal reflux disease with esophagitis",
            "Diaphragmatic hernia without obstruction or gangrene",
        ],
        "requested_date": "2024-10-28",
        "determination_date": "2024-10-30",
        "expiration_date": "2025-01-30",
        "clinical_reviewer": "Auto-approved",
        "reviewer_notes": "Auto-approved per plan guidelines. Upper GI endoscopy with biopsy does not require prior authorization under this PPO plan for in-network providers. Notification recorded for tracking purposes only.",
        "facility": "Texas Health Presbyterian Hospital",
        "estimated_cost": 3200.00,
        "urgency": "routine",
    },
    "PA-2024-00589": {
        "reference_id": "PA-2024-00589",
        "status": "approved",
        "patient_name": "Patricia Nakamura",
        "patient_dob": "1978-12-03",
        "member_id": "HMO-445621",
        "provider_npi": "6789012345",
        "provider_name": "Dr. David Lee, MD — Neurology",
        "payer": "Kaiser Permanente",
        "plan_type": "HMO",
        "cpt_code": "95819",
        "cpt_description": "Electroencephalogram (EEG) with sleep",
        "icd10_codes": ["G40.909"],
        "icd10_descriptions": ["Epilepsy, unspecified, not intractable, without status epilepticus"],
        "requested_date": "2024-11-05",
        "determination_date": "2024-11-06",
        "expiration_date": "2025-02-06",
        "clinical_reviewer": "Auto-approved",
        "reviewer_notes": "Auto-approved. EEG with sleep is a covered diagnostic procedure under HMO plan. Prior authorization not required; notification accepted.",
        "facility": "Kaiser Permanente Los Angeles Medical Center",
        "estimated_cost": 1850.00,
        "urgency": "routine",
    },
    "PA-2024-00634": {
        "reference_id": "PA-2024-00634",
        "status": "denied",
        "patient_name": "Carlos Rivera",
        "patient_dob": "1982-04-25",
        "member_id": "PPO-331087",
        "provider_npi": "7890123456",
        "provider_name": "Dr. Susan Blackwell, MD — Plastic Surgery",
        "payer": "Humana",
        "plan_type": "PPO",
        "cpt_code": "15830",
        "cpt_description": "Excision of excessive skin and subcutaneous tissue (abdominoplasty)",
        "icd10_codes": ["L98.9"],
        "icd10_descriptions": ["Disorder of the skin and subcutaneous tissue, unspecified"],
        "requested_date": "2024-10-15",
        "determination_date": "2024-10-22",
        "expiration_date": None,
        "clinical_reviewer": "Dr. Karen Wells, MD — Utilization Review",
        "reviewer_notes": "Denied — classified as cosmetic procedure. ICD-10 code L98.9 is nonspecific and does not establish medical necessity. No documentation of panniculitis, recurrent skin infections, or functional impairment. If the procedure is medically necessary (e.g., post-bariatric surgery with documented complications), resubmit with supporting clinical documentation and appropriate ICD-10 code.",
        "facility": "Emory University Hospital",
        "estimated_cost": 12400.00,
        "urgency": "elective",
    },
    "PA-2024-00701": {
        "reference_id": "PA-2024-00701",
        "status": "pending",
        "patient_name": "Eleanor Fitzpatrick",
        "patient_dob": "1948-09-11",
        "member_id": "MA-776543",
        "provider_npi": "8901234567",
        "provider_name": "Dr. Kevin Nguyen, MD — Pulmonology",
        "payer": "Medicare Advantage (Humana Gold Plus)",
        "plan_type": "Medicare Advantage",
        "cpt_code": "31623",
        "cpt_description": "Bronchoscopy with brushing or protected brushings",
        "icd10_codes": ["R91.1", "J44.1"],
        "icd10_descriptions": [
            "Solitary pulmonary nodule",
            "Chronic obstructive pulmonary disease with acute exacerbation",
        ],
        "requested_date": "2024-11-18",
        "determination_date": None,
        "expiration_date": None,
        "clinical_reviewer": None,
        "reviewer_notes": "Under clinical review. CT scan shows 12mm solitary pulmonary nodule in right upper lobe. Patient has 40 pack-year smoking history. Awaiting radiology second read and PET scan results before determination. Expedited review requested due to patient age and clinical presentation.",
        "facility": "Mayo Clinic — Rochester",
        "estimated_cost": 5600.00,
        "urgency": "urgent",
    },
    "PA-2024-00819": {
        "reference_id": "PA-2024-00819",
        "status": "expired",
        "patient_name": "Thomas Brennan",
        "patient_dob": "1969-07-02",
        "member_id": "PPO-223344",
        "provider_npi": "4567890123",
        "provider_name": "Dr. Lisa Franklin, MD — Orthopedic Surgery",
        "payer": "Anthem Blue Cross",
        "plan_type": "PPO",
        "cpt_code": "29881",
        "cpt_description": "Arthroscopy, knee, surgical; with meniscectomy",
        "icd10_codes": ["M23.211"],
        "icd10_descriptions": ["Derangement of anterior horn of medial meniscus due to old tear or injury, right knee"],
        "requested_date": "2024-06-10",
        "determination_date": "2024-06-17",
        "expiration_date": "2024-09-17",
        "clinical_reviewer": "Dr. Alan Jacobs, MD — Utilization Review",
        "reviewer_notes": "Originally approved 2024-06-17. Authorization expired 2024-09-17 — procedure was not performed within the 90-day authorization window. Provider must submit a new prior authorization request if surgery is still indicated. Updated clinical documentation required.",
        "facility": "Cedars-Sinai Medical Center",
        "estimated_cost": 15200.00,
        "urgency": "elective",
    },
    "PA-2024-00955": {
        "reference_id": "PA-2024-00955",
        "status": "partially-approved",
        "patient_name": "Sandra Kim",
        "patient_dob": "1995-02-28",
        "member_id": "HMO-889100",
        "provider_npi": "5678901234",
        "provider_name": "Dr. William Okafor, MD — Physical Medicine & Rehabilitation",
        "payer": "Molina Healthcare",
        "plan_type": "Medicaid HMO",
        "cpt_code": "97110",
        "cpt_description": "Therapeutic exercises, each 15 minutes",
        "icd10_codes": ["S83.511A", "M25.561"],
        "icd10_descriptions": [
            "Sprain of anterior cruciate ligament of right knee, initial encounter",
            "Stiffness of right knee, not elsewhere classified",
        ],
        "requested_date": "2024-11-10",
        "determination_date": "2024-11-14",
        "expiration_date": "2025-02-14",
        "clinical_reviewer": "Dr. Michelle Adams, RN — Case Manager",
        "reviewer_notes": "Partially approved. Provider requested 36 sessions of PT over 12 weeks. Approved for 18 sessions over 6 weeks. Re-evaluation and updated plan of care required at session 18 for continued authorization. Patient must attend minimum 2 sessions per week to maintain authorization.",
        "facility": "Select Physical Therapy — Outpatient Clinic",
        "estimated_cost": 4320.00,
        "urgency": "routine",
    },
}
