"""
Mock B2B Ecommerce Order Records
==================================
This module contains simulated purchase order data for the B2B Order Status
Bot agent. Each record represents a purchase order placed by a business
customer through a B2B ecommerce platform.

In production, this data would come from an ERP system (e.g., SAP, NetSuite,
Oracle) or an Order Management System (OMS) via a REST API.
"""

ORDER_RECORDS = {
    "PO-2024-8847": {
        "po_number": "PO-2024-8847",
        "status": "shipped",
        "customer_name": "Apex Manufacturing Co.",
        "customer_account": "ACCT-10042",
        "order_date": "2024-10-28",
        "ship_date": "2024-11-02",
        "estimated_delivery": "2024-11-06",
        "actual_delivery": None,
        "carrier": "FedEx Freight",
        "tracking_number": "7489-3920-4817",
        "shipping_method": "LTL Freight",
        "warehouse": "Chicago Distribution Center (ORD-DC3)",
        "line_items": [
            {
                "sku": "IND-VALVE-3200",
                "description": "3-inch Industrial Ball Valve, SS316",
                "quantity": 50,
                "unit_price": 87.50,
                "line_total": 4375.00,
                "status": "shipped",
            },
            {
                "sku": "GASKET-FLG-3IN",
                "description": "3-inch Flange Gasket, PTFE",
                "quantity": 100,
                "unit_price": 12.30,
                "line_total": 1230.00,
                "status": "shipped",
            },
        ],
        "subtotal": 5605.00,
        "tax": 0.00,
        "shipping_cost": 285.00,
        "total": 5890.00,
        "payment_terms": "Net 30",
        "payment_status": "invoiced",
        "notes": "All items shipped in single shipment. Signature required on delivery.",
    },
    "PO-2024-9103": {
        "po_number": "PO-2024-9103",
        "status": "processing",
        "customer_name": "Greenfield Building Supply",
        "customer_account": "ACCT-10187",
        "order_date": "2024-11-15",
        "ship_date": None,
        "estimated_delivery": "2024-11-25",
        "actual_delivery": None,
        "carrier": None,
        "tracking_number": None,
        "shipping_method": "Flatbed Truck",
        "warehouse": "Dallas Distribution Center (DFW-DC1)",
        "line_items": [
            {
                "sku": "LUMBER-2X4-8FT",
                "description": "Dimensional Lumber, 2x4, 8ft, #2 Grade SYP",
                "quantity": 500,
                "unit_price": 5.85,
                "line_total": 2925.00,
                "status": "picking",
            },
            {
                "sku": "PLY-CDX-4X8-0.75",
                "description": "CDX Plywood, 4x8 Sheet, 3/4 inch",
                "quantity": 200,
                "unit_price": 42.00,
                "line_total": 8400.00,
                "status": "picking",
            },
            {
                "sku": "CONC-REBAR-NO4",
                "description": "#4 Rebar, 20ft length, Grade 60",
                "quantity": 300,
                "unit_price": 14.70,
                "line_total": 4410.00,
                "status": "awaiting-stock",
            },
        ],
        "subtotal": 15735.00,
        "tax": 0.00,
        "shipping_cost": 950.00,
        "total": 16685.00,
        "payment_terms": "Net 45",
        "payment_status": "pending",
        "notes": "Rebar on backorder from mill — expected in stock 2024-11-20. Partial shipment option declined by customer.",
    },
    "PO-2024-8512": {
        "po_number": "PO-2024-8512",
        "status": "delivered",
        "customer_name": "Pacific Coast Electronics",
        "customer_account": "ACCT-10305",
        "order_date": "2024-10-10",
        "ship_date": "2024-10-14",
        "estimated_delivery": "2024-10-18",
        "actual_delivery": "2024-10-17",
        "carrier": "UPS Freight",
        "tracking_number": "1Z999AA10123456784",
        "shipping_method": "Ground",
        "warehouse": "Reno Distribution Center (RNO-DC2)",
        "line_items": [
            {
                "sku": "PCB-FR4-6L",
                "description": "6-Layer FR-4 PCB Blank, 12x18 inch",
                "quantity": 1000,
                "unit_price": 3.45,
                "line_total": 3450.00,
                "status": "delivered",
            },
            {
                "sku": "SMD-RES-KIT-0805",
                "description": "SMD Resistor Kit, 0805, 170 values",
                "quantity": 20,
                "unit_price": 28.50,
                "line_total": 570.00,
                "status": "delivered",
            },
        ],
        "subtotal": 4020.00,
        "tax": 0.00,
        "shipping_cost": 145.00,
        "total": 4165.00,
        "payment_terms": "Net 30",
        "payment_status": "paid",
        "notes": "Delivered one day early. Signed by J. Tanaka at receiving dock.",
    },
    "PO-2024-9250": {
        "po_number": "PO-2024-9250",
        "status": "backordered",
        "customer_name": "Summit HVAC Solutions",
        "customer_account": "ACCT-10089",
        "order_date": "2024-11-10",
        "ship_date": None,
        "estimated_delivery": "2024-12-15",
        "actual_delivery": None,
        "carrier": None,
        "tracking_number": None,
        "shipping_method": "LTL Freight",
        "warehouse": "Atlanta Distribution Center (ATL-DC1)",
        "line_items": [
            {
                "sku": "COMPRESSOR-5TON",
                "description": "Scroll Compressor, 5-Ton, R-410A, 208-230V",
                "quantity": 10,
                "unit_price": 1245.00,
                "line_total": 12450.00,
                "status": "backordered",
            },
            {
                "sku": "COIL-EVAP-5TON",
                "description": "Evaporator Coil, 5-Ton, Upflow/Downflow",
                "quantity": 10,
                "unit_price": 485.00,
                "line_total": 4850.00,
                "status": "backordered",
            },
        ],
        "subtotal": 17300.00,
        "tax": 0.00,
        "shipping_cost": 620.00,
        "total": 17920.00,
        "payment_terms": "Net 60",
        "payment_status": "pending",
        "notes": "Manufacturer supply chain disruption. Compressors expected from factory 2024-12-05. Customer notified of delay on 2024-11-12. SLA credit of 2% applied.",
    },
    "PO-2024-7891": {
        "po_number": "PO-2024-7891",
        "status": "cancelled",
        "customer_name": "Redwood Agricultural Equipment",
        "customer_account": "ACCT-10421",
        "order_date": "2024-09-15",
        "ship_date": None,
        "estimated_delivery": None,
        "actual_delivery": None,
        "carrier": None,
        "tracking_number": None,
        "shipping_method": "Flatbed Truck",
        "warehouse": "Sacramento Distribution Center (SMF-DC1)",
        "line_items": [
            {
                "sku": "PUMP-CENT-15HP",
                "description": "Centrifugal Irrigation Pump, 15HP, 6-inch Discharge",
                "quantity": 3,
                "unit_price": 4250.00,
                "line_total": 12750.00,
                "status": "cancelled",
            },
        ],
        "subtotal": 12750.00,
        "tax": 0.00,
        "shipping_cost": 0.00,
        "total": 12750.00,
        "payment_terms": "Net 30",
        "payment_status": "refunded",
        "notes": "Cancelled by customer on 2024-09-20. Reason: project funding withdrawn. No restocking fee per account agreement. Full refund processed 2024-09-25.",
    },
    "PO-2024-9401": {
        "po_number": "PO-2024-9401",
        "status": "partially-shipped",
        "customer_name": "Metro Plumbing & Mechanical",
        "customer_account": "ACCT-10156",
        "order_date": "2024-11-08",
        "ship_date": "2024-11-12",
        "estimated_delivery": "2024-11-18",
        "actual_delivery": None,
        "carrier": "XPO Logistics",
        "tracking_number": "XPO-842719305",
        "shipping_method": "LTL Freight",
        "warehouse": "Newark Distribution Center (EWR-DC2)",
        "line_items": [
            {
                "sku": "PIPE-CU-2IN-L",
                "description": "Type L Copper Pipe, 2-inch, 10ft length",
                "quantity": 100,
                "unit_price": 64.80,
                "line_total": 6480.00,
                "status": "shipped",
            },
            {
                "sku": "FITTING-CU-2IN-ELB",
                "description": "Copper Elbow Fitting, 2-inch, 90-degree",
                "quantity": 200,
                "unit_price": 8.95,
                "line_total": 1790.00,
                "status": "shipped",
            },
            {
                "sku": "WH-COMM-100GAL",
                "description": "Commercial Water Heater, 100-Gallon, Natural Gas",
                "quantity": 2,
                "unit_price": 3850.00,
                "line_total": 7700.00,
                "status": "processing",
            },
        ],
        "subtotal": 15970.00,
        "tax": 0.00,
        "shipping_cost": 510.00,
        "total": 16480.00,
        "payment_terms": "Net 30",
        "payment_status": "invoiced",
        "notes": "Pipe and fittings shipped. Water heaters require factory drop-ship — estimated ship date 2024-11-20 direct from manufacturer.",
    },
    "PO-2024-8200": {
        "po_number": "PO-2024-8200",
        "status": "delivered",
        "customer_name": "Sterling Office Interiors",
        "customer_account": "ACCT-10500",
        "order_date": "2024-09-25",
        "ship_date": "2024-09-30",
        "estimated_delivery": "2024-10-04",
        "actual_delivery": "2024-10-04",
        "carrier": "ABF Freight",
        "tracking_number": "ABF-20241004-7791",
        "shipping_method": "LTL Freight",
        "warehouse": "Chicago Distribution Center (ORD-DC3)",
        "line_items": [
            {
                "sku": "DESK-SIT-STAND-72",
                "description": "Electric Sit-Stand Desk, 72x30 inch, White Laminate",
                "quantity": 25,
                "unit_price": 549.00,
                "line_total": 13725.00,
                "status": "delivered",
            },
            {
                "sku": "CHAIR-ERGO-MESH",
                "description": "Ergonomic Mesh Task Chair, Adjustable Arms",
                "quantity": 25,
                "unit_price": 379.00,
                "line_total": 9475.00,
                "status": "delivered",
            },
            {
                "sku": "MON-ARM-DUAL",
                "description": "Dual Monitor Arm, Clamp Mount, 27-inch capacity",
                "quantity": 25,
                "unit_price": 89.00,
                "line_total": 2225.00,
                "status": "delivered",
            },
        ],
        "subtotal": 25425.00,
        "tax": 0.00,
        "shipping_cost": 780.00,
        "total": 26205.00,
        "payment_terms": "Net 30",
        "payment_status": "paid",
        "notes": "White glove delivery to 15th floor. Installation completed by vendor crew. All items inspected and accepted by facilities manager.",
    },
    "PO-2024-9550": {
        "po_number": "PO-2024-9550",
        "status": "on-hold",
        "customer_name": "Cascade Chemical Supply",
        "customer_account": "ACCT-10278",
        "order_date": "2024-11-18",
        "ship_date": None,
        "estimated_delivery": None,
        "actual_delivery": None,
        "carrier": None,
        "tracking_number": None,
        "shipping_method": "Hazmat Carrier — TBD",
        "warehouse": "Houston Distribution Center (IAH-DC1)",
        "line_items": [
            {
                "sku": "CHEM-NaOH-50PCT",
                "description": "Sodium Hydroxide Solution, 50%, 55-gallon drum",
                "quantity": 10,
                "unit_price": 320.00,
                "line_total": 3200.00,
                "status": "on-hold",
            },
            {
                "sku": "CHEM-HCL-37PCT",
                "description": "Hydrochloric Acid, 37%, 55-gallon drum",
                "quantity": 5,
                "unit_price": 275.00,
                "line_total": 1375.00,
                "status": "on-hold",
            },
        ],
        "subtotal": 4575.00,
        "tax": 0.00,
        "shipping_cost": 1250.00,
        "total": 5825.00,
        "payment_terms": "Net 30",
        "payment_status": "pending",
        "notes": "Order on hold — pending updated HAZMAT shipping certification for delivery address. Customer's SDS file on record but carrier requires current DOT placarding confirmation. Expected clearance 2024-11-22.",
    },
    "PO-2024-9612": {
        "po_number": "PO-2024-9612",
        "status": "processing",
        "customer_name": "NovaTech Robotics Inc.",
        "customer_account": "ACCT-10334",
        "order_date": "2024-11-19",
        "ship_date": None,
        "estimated_delivery": "2024-11-28",
        "actual_delivery": None,
        "carrier": None,
        "tracking_number": None,
        "shipping_method": "Air Freight",
        "warehouse": "Reno Distribution Center (RNO-DC2)",
        "line_items": [
            {
                "sku": "SERVO-NEMA34-12NM",
                "description": "Closed-Loop Servo Motor, NEMA 34, 12 N.m",
                "quantity": 6,
                "unit_price": 289.00,
                "line_total": 1734.00,
                "status": "packing",
            },
            {
                "sku": "DRIVER-SERVO-AC",
                "description": "AC Servo Driver, 3-Phase, 2kW",
                "quantity": 6,
                "unit_price": 195.00,
                "line_total": 1170.00,
                "status": "packing",
            },
            {
                "sku": "ENCODER-ABS-17BIT",
                "description": "Absolute Encoder, 17-bit, Multi-turn",
                "quantity": 6,
                "unit_price": 142.00,
                "line_total": 852.00,
                "status": "quality-check",
            },
        ],
        "subtotal": 3756.00,
        "tax": 0.00,
        "shipping_cost": 425.00,
        "total": 4181.00,
        "payment_terms": "Net 30",
        "payment_status": "pending",
        "notes": "Air freight requested — customer needs parts for production line commissioning. Encoders undergoing outgoing quality inspection. Expected to ship 2024-11-21.",
    },
    "PO-2024-8005": {
        "po_number": "PO-2024-8005",
        "status": "returned",
        "customer_name": "Midwest Fabrication Works",
        "customer_account": "ACCT-10067",
        "order_date": "2024-09-05",
        "ship_date": "2024-09-09",
        "estimated_delivery": "2024-09-13",
        "actual_delivery": "2024-09-13",
        "carrier": "Estes Express Lines",
        "tracking_number": "EST-09130045629",
        "shipping_method": "LTL Freight",
        "warehouse": "Chicago Distribution Center (ORD-DC3)",
        "line_items": [
            {
                "sku": "STEEL-PLATE-0.5IN",
                "description": "A36 Steel Plate, 0.5-inch, 4x8 ft",
                "quantity": 20,
                "unit_price": 385.00,
                "line_total": 7700.00,
                "status": "returned",
            },
        ],
        "subtotal": 7700.00,
        "tax": 0.00,
        "shipping_cost": 890.00,
        "total": 8590.00,
        "payment_terms": "Net 30",
        "payment_status": "credit-issued",
        "notes": "Material rejected at receiving inspection — plates showed surface pitting and mill scale not within spec. RMA #RMA-2024-0334 issued. Replacement order PO-2024-8112 placed. Full credit issued including original shipping cost.",
    },
}
