"""The PostgreSQL target guard.

The Oracle guard says "no writes at all". This one is harder, because the
migration's whole job is to write -- it has to allow the right writes and
refuse the wrong ones. Two rules: nothing gets dropped, and nothing gets
created outside the staging schema.

The second rule is what makes cutover a single atomic `ALTER SCHEMA
... RENAME`. One object accidentally created in `public` and the rename
either collides or leaves an orphan.
"""

from __future__ import annotations

import pytest
from claude_agent_sdk import PermissionResultAllow, PermissionResultDeny

from hooks import protect_pg_target

PG_DDL = "mcp__pg_target__pg_apply_ddl"


async def _decide(ddl: str):
    return await protect_pg_target(PG_DDL, {"ddl": ddl}, None)


# --------------------------------------------------------------- denied
@pytest.mark.asyncio
@pytest.mark.parametrize(
    "ddl",
    [
        "DROP SCHEMA public CASCADE",
        "drop schema ucc_migrated cascade",
        "DROP DATABASE meridian",
        "DROP OWNED BY migration",
        "DROP ROLE migration",
        "DROP TABLESPACE pg_default",
    ],
)
async def test_drops_are_denied(ddl):
    result = await _decide(ddl)
    assert isinstance(result, PermissionResultDeny), f"{ddl!r} was allowed"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "ddl",
    [
        "CREATE TABLE public.ucc_filing (filing_id bigint)",
        "CREATE TABLE pg_catalog.sneaky (id int)",
        "ALTER TABLE public.ucc_debtor ADD COLUMN x text",
        'CREATE INDEX "public".ix_x ON y (z)',
    ],
)
async def test_objects_outside_target_schema_are_denied(ddl):
    result = await _decide(ddl)
    assert isinstance(result, PermissionResultDeny), f"{ddl!r} was allowed"
    assert "ucc_migrated" in result.message


# -------------------------------------------------------------- allowed
@pytest.mark.asyncio
@pytest.mark.parametrize(
    "ddl",
    [
        # Unqualified: search_path puts it in the target schema.
        "CREATE TABLE ucc_filing (filing_id bigint GENERATED BY DEFAULT AS IDENTITY)",
        # Explicitly qualified into the target.
        "CREATE TABLE ucc_migrated.ucc_debtor (debtor_id bigint)",
        "ALTER TABLE ucc_migrated.ucc_filing ADD CONSTRAINT pk PRIMARY KEY (filing_id)",
        "CREATE INDEX ix_filing_state ON ucc_filing (state_code, filed_date)",
        "CREATE OR REPLACE FUNCTION ucc_migrated.score(x text) RETURNS numeric AS $$ $$ LANGUAGE sql",
    ],
)
async def test_legitimate_migration_ddl_is_allowed(ddl):
    result = await _decide(ddl)
    assert isinstance(result, PermissionResultAllow), f"{ddl!r} was denied"


@pytest.mark.asyncio
async def test_guard_ignores_other_tools():
    """pg_query and pg_copy_load are not this guard's business."""
    result = await protect_pg_target(
        "mcp__pg_target__pg_query", {"sql": "DROP SCHEMA public"}, None
    )
    assert isinstance(result, PermissionResultAllow)


@pytest.mark.asyncio
async def test_empty_ddl_is_not_an_error():
    result = await _decide("")
    assert isinstance(result, PermissionResultAllow)
