"""
M22B — Pydantic Models for the UCC Agent API
===============================================
Complete — do not modify.

These models define the request/response contracts for the API.
They enforce validation, generate OpenAPI docs automatically,
and provide type safety throughout the application.
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Request Models
# ---------------------------------------------------------------------------

class QueryRequest(BaseModel):
    """Request body for the /query and /query/stream endpoints."""

    query: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="The natural-language research query about UCC filings.",
        examples=["Find all UCC filings for Acme Corporation in New York"],
    )
    state: Optional[str] = Field(
        None,
        description="Optional state filter (e.g., 'New York', 'California').",
    )
    include_risk: bool = Field(
        False,
        description="If True, include risk analysis in the response.",
    )
    max_results: int = Field(
        10,
        ge=1,
        le=50,
        description="Maximum number of filings to return.",
    )


# ---------------------------------------------------------------------------
# Response Models
# ---------------------------------------------------------------------------

class FilingSummary(BaseModel):
    """Summary of a single UCC filing."""

    filing_number: str
    filing_type: str
    state: str
    status: str
    debtor_name: str
    secured_party_name: str
    filing_date: str
    collateral_summary: str


class RiskSummary(BaseModel):
    """Risk assessment summary."""

    risk_score: float = Field(..., ge=0.0, le=100.0)
    risk_level: str  # "Low", "Medium", "High", "Critical"
    total_liens: int
    states_with_filings: int
    recommendation: str


class QueryResponse(BaseModel):
    """Response body for the /query endpoint."""

    query: str
    answer: str
    filings: list[FilingSummary] = Field(default_factory=list)
    risk: Optional[RiskSummary] = None
    processing_time_ms: float
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    mock_mode: bool = Field(
        False,
        description="True if the response was generated by the mock agent.",
    )


class HealthResponse(BaseModel):
    """Response body for the /health endpoint."""

    status: str = "healthy"
    version: str = "1.0.0"
    environment: str = "development"
    mock_mode: bool = False
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class StreamChunk(BaseModel):
    """A single chunk in a Server-Sent Events stream."""

    event: str = Field(
        ...,
        description="Event type: 'chunk', 'filing', 'risk', 'done', or 'error'.",
    )
    data: str = Field(
        ...,
        description="The chunk content (text for 'chunk', JSON for structured events).",
    )


class ErrorResponse(BaseModel):
    """Standardized error response."""

    error: str
    detail: str
    status_code: int
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
