"""
Mock data for Capstone 5 — Production Agent: Autonomous UCC Data Engineering Platform.

Contains:
- 50+ UCC filings across 5 states (NY, DE, CA, TX, FL)
- 15 business entities in the registry
- Realistic collateral descriptions with legal language
- Edge cases: expired filings, name variations, multiple secured parties,
  terminated filings, continuation statements, and ambiguous collateral
"""

from datetime import date

# ---------------------------------------------------------------------------
# UCC Filings Database — 54 filings across NY, DE, CA, TX, FL
# ---------------------------------------------------------------------------
UCC_FILINGS = {
    # -----------------------------------------------------------------------
    # NEW YORK (11 filings)
    # -----------------------------------------------------------------------
    "NY": {
        "NY-2023-0558291": {
            "filing_number": "NY-2023-0558291", "state": "NY", "filing_type": "UCC-1",
            "filing_date": "2023-07-18", "lapse_date": "2028-07-18",
            "debtor_name": "Acme Corporation",
            "debtor_address": "350 Fifth Avenue, Suite 5100, New York, NY 10118",
            "debtor_ein": "94-3829471",
            "secured_party": "Manhattan Commercial Finance",
            "secured_party_address": "40 Wall Street, 28th Floor, New York, NY 10005",
            "collateral": "Accounts receivable, contract rights, and general intangibles now owned or hereafter acquired",
            "status": "active",
            "amendments": [],
        },
        "NY-2022-0341829": {
            "filing_number": "NY-2022-0341829", "state": "NY", "filing_type": "UCC-1",
            "filing_date": "2022-12-05", "lapse_date": "2027-12-05",
            "debtor_name": "Pinnacle Systems International",
            "debtor_address": "One Penn Plaza, Suite 2200, New York, NY 10119",
            "debtor_ein": "95-7712034",
            "secured_party": "JPMorgan Chase Commercial Banking",
            "secured_party_address": "383 Madison Avenue, New York, NY 10179",
            "collateral": "All inventory, equipment, accounts, chattel paper, instruments, and general intangibles",
            "status": "active",
            "amendments": [
                {"number": "NY-2024-AMD-001", "date": "2024-01-15", "type": "assignment",
                 "description": "Assignment of security interest to Chase Capital Markets LLC"},
            ],
        },
        "NY-2021-0189234": {
            "filing_number": "NY-2021-0189234", "state": "NY", "filing_type": "UCC-1",
            "filing_date": "2021-04-10", "lapse_date": "2026-04-10",
            "debtor_name": "Greenfield Organics Inc",
            "debtor_address": "88 Pine Street, Suite 1200, New York, NY 10005",
            "debtor_ein": "13-5529843",
            "secured_party": "New York Business Credit Corp",
            "secured_party_address": "120 Broadway, Suite 3500, New York, NY 10271",
            "collateral": "All inventory consisting of organic food products, packaging materials, and related supplies; all accounts receivable arising from the sale thereof",
            "status": "active",
            "amendments": [],
        },
        "NY-2024-0078451": {
            "filing_number": "NY-2024-0078451", "state": "NY", "filing_type": "UCC-1",
            "filing_date": "2024-02-14", "lapse_date": "2029-02-14",
            "debtor_name": "Greenfield Organic Foods",
            "debtor_address": "88 Pine Street, Suite 1200, New York, NY 10005",
            "debtor_ein": "13-5529843",
            "secured_party": "Empire State Lending Partners",
            "secured_party_address": "1 Liberty Plaza, New York, NY 10006",
            "collateral": "Equipment, furniture, and fixtures located at 88 Pine Street, Suite 1200, New York, NY 10005",
            "status": "active",
            "amendments": [],
        },
        "NY-2020-0445192": {
            "filing_number": "NY-2020-0445192", "state": "NY", "filing_type": "UCC-1",
            "filing_date": "2020-09-22", "lapse_date": "2025-09-22",
            "debtor_name": "Vertex Capital Advisors LLC",
            "debtor_address": "200 Park Avenue, Suite 3100, New York, NY 10166",
            "debtor_ein": "13-8847291",
            "secured_party": "Goldman Sachs Lending Partners",
            "secured_party_address": "200 West Street, New York, NY 10282",
            "collateral": "All assets of the Debtor, including but not limited to accounts, chattel paper, commercial tort claims, deposit accounts, equipment, general intangibles, goods, instruments, inventory, investment property, and letter-of-credit rights",
            "status": "active",
            "amendments": [
                {"number": "NY-2023-AMD-002", "date": "2023-09-01", "type": "continuation",
                 "description": "Continuation statement filed — extends lapse date to 2030-09-22"},
            ],
        },
        "NY-2019-0892341": {
            "filing_number": "NY-2019-0892341", "state": "NY", "filing_type": "UCC-1",
            "filing_date": "2019-03-15", "lapse_date": "2024-03-15",
            "debtor_name": "Metro Construction Holdings Inc",
            "debtor_address": "450 Lexington Avenue, Suite 1800, New York, NY 10017",
            "debtor_ein": "13-6672190",
            "secured_party": "Citibank Commercial Lending",
            "secured_party_address": "388 Greenwich Street, New York, NY 10013",
            "collateral": "Construction equipment, vehicles, and heavy machinery as described in Schedule A attached hereto",
            "status": "lapsed",
            "amendments": [],
        },
        "NY-2023-0912847": {
            "filing_number": "NY-2023-0912847", "state": "NY", "filing_type": "UCC-1",
            "filing_date": "2023-10-05", "lapse_date": "2028-10-05",
            "debtor_name": "Metro Construction Holdings",
            "debtor_address": "450 Lexington Avenue, Suite 1800, New York, NY 10017",
            "debtor_ein": "13-6672190",
            "secured_party": "Bank of America Business Capital",
            "secured_party_address": "One Bryant Park, New York, NY 10036",
            "collateral": "All accounts receivable and rights to payment under government construction contracts",
            "status": "active",
            "amendments": [],
        },
        "NY-2024-0134892": {
            "filing_number": "NY-2024-0134892", "state": "NY", "filing_type": "UCC-1",
            "filing_date": "2024-03-28", "lapse_date": "2029-03-28",
            "debtor_name": "Cascade Technologies Corp",
            "debtor_address": "100 Wall Street, Suite 800, New York, NY 10005",
            "debtor_ein": "13-9923847",
            "secured_party": "Silicon Valley Bank (a division of First Citizens BancShares)",
            "secured_party_address": "3003 Tasman Drive, Santa Clara, CA 95054",
            "collateral": "All intellectual property, including patents, trademarks, copyrights, trade secrets, and all licenses and royalties related thereto",
            "status": "active",
            "amendments": [],
        },
        "NY-2022-0667283": {
            "filing_number": "NY-2022-0667283", "state": "NY", "filing_type": "UCC-1",
            "filing_date": "2022-06-30", "lapse_date": "2027-06-30",
            "debtor_name": "Apex Marine Services LLC",
            "debtor_address": "17 Battery Place, Suite 600, New York, NY 10004",
            "debtor_ein": "13-4418927",
            "secured_party": "Maritime Capital Partners",
            "secured_party_address": "28 Liberty Street, New York, NY 10005",
            "collateral": "Marine vessels identified as: MV Atlantic Pioneer (IMO 9834521), MV Harbor Sentinel (IMO 9834522); all appurtenances, fittings, and equipment thereon",
            "status": "active",
            "amendments": [],
        },
        "NY-2023-0781924": {
            "filing_number": "NY-2023-0781924", "state": "NY", "filing_type": "UCC-3",
            "filing_date": "2023-08-15", "lapse_date": None,
            "debtor_name": "Apex Marine Services LLC",
            "debtor_address": "17 Battery Place, Suite 600, New York, NY 10004",
            "debtor_ein": "13-4418927",
            "secured_party": "Maritime Capital Partners",
            "secured_party_address": "28 Liberty Street, New York, NY 10005",
            "collateral": "Termination of filing NY-2022-0667283 as to MV Harbor Sentinel (IMO 9834522) only",
            "status": "terminated_partial",
            "amendments": [],
            "related_filing": "NY-2022-0667283",
        },
        "NY-2024-0201934": {
            "filing_number": "NY-2024-0201934", "state": "NY", "filing_type": "UCC-1",
            "filing_date": "2024-04-02", "lapse_date": "2029-04-02",
            "debtor_name": "Helix Biotech Partners LP",
            "debtor_address": "430 East 29th Street, Suite 14A, New York, NY 10016",
            "debtor_ein": "13-7756123",
            "secured_party": "Perceptive Advisors LLC",
            "secured_party_address": "51 Astor Place, 10th Floor, New York, NY 10003",
            "collateral": "All assets of the Debtor including FDA-approved and pipeline pharmaceutical products, clinical trial data, and associated intellectual property",
            "status": "active",
            "amendments": [],
        },
    },

    # -----------------------------------------------------------------------
    # DELAWARE (12 filings)
    # -----------------------------------------------------------------------
    "DE": {
        "DE-2021-0091447": {
            "filing_number": "DE-2021-0091447", "state": "DE", "filing_type": "UCC-1",
            "filing_date": "2021-09-30", "lapse_date": "2026-09-30",
            "debtor_name": "Acme Corp",
            "debtor_address": "1209 Orange Street, Wilmington, DE 19801",
            "debtor_ein": "94-3829471",
            "secured_party": "Delaware Trust Financial",
            "secured_party_address": "100 West 10th Street, Wilmington, DE 19801",
            "collateral": "All assets now owned or hereafter acquired, including but not limited to accounts, chattel paper, deposit accounts, equipment, general intangibles, goods, instruments, inventory, and investment property",
            "status": "active",
            "amendments": [
                {"number": "DE-2023-AMD-001", "date": "2023-03-01", "type": "debtor_name_change",
                 "description": "Debtor name updated from 'Acme Corp' to 'Acme Corporation' per entity name change filed with DE SOS"},
            ],
        },
        "DE-2023-0145592": {
            "filing_number": "DE-2023-0145592", "state": "DE", "filing_type": "UCC-1",
            "filing_date": "2023-05-14", "lapse_date": "2028-05-14",
            "debtor_name": "Trident Logistics Group LLC",
            "debtor_address": "300 Delaware Avenue, Suite 900, Wilmington, DE 19801",
            "debtor_ein": "51-0482193",
            "secured_party": "Citizens Business Capital",
            "secured_party_address": "1 Citizens Drive, Riverside, RI 02915",
            "collateral": "Fleet vehicles, transportation equipment, and related assets including but not limited to tractors, trailers, and refrigeration units",
            "status": "active",
            "amendments": [],
        },
        "DE-2024-0023891": {
            "filing_number": "DE-2024-0023891", "state": "DE", "filing_type": "UCC-1",
            "filing_date": "2024-01-08", "lapse_date": "2029-01-08",
            "debtor_name": "Trident Logistics Group (formerly Pinnacle Transport Services)",
            "debtor_address": "300 Delaware Avenue, Suite 900, Wilmington, DE 19801",
            "debtor_ein": "51-0482193",
            "secured_party": "Wells Fargo Equipment Finance",
            "secured_party_address": "1 Wells Fargo Center, Charlotte, NC 28202",
            "collateral": "Specific equipment: Refrigerated trailers VIN/Serial numbers RFT-001 through RFT-050",
            "status": "active",
            "amendments": [],
        },
        "DE-2022-0078123": {
            "filing_number": "DE-2022-0078123", "state": "DE", "filing_type": "UCC-1",
            "filing_date": "2022-03-20", "lapse_date": "2027-03-20",
            "debtor_name": "Vertex Capital Advisors",
            "debtor_address": "1201 North Market Street, Suite 1800, Wilmington, DE 19801",
            "debtor_ein": "13-8847291",
            "secured_party": "Morgan Stanley Private Credit",
            "secured_party_address": "1585 Broadway, New York, NY 10036",
            "collateral": "Securities accounts maintained at Morgan Stanley, including all investment property, financial assets, and proceeds thereof",
            "status": "active",
            "amendments": [],
        },
        "DE-2023-0198234": {
            "filing_number": "DE-2023-0198234", "state": "DE", "filing_type": "UCC-1",
            "filing_date": "2023-08-22", "lapse_date": "2028-08-22",
            "debtor_name": "Cascade Technologies Corporation",
            "debtor_address": "1209 Orange Street, Wilmington, DE 19801",
            "debtor_ein": "13-9923847",
            "secured_party": "Horizon Venture Debt LLC",
            "secured_party_address": "2180 Sand Hill Road, Menlo Park, CA 94025",
            "collateral": "All assets of the Debtor, including all intellectual property rights and all revenue derived therefrom",
            "status": "active",
            "amendments": [],
        },
        "DE-2020-0056781": {
            "filing_number": "DE-2020-0056781", "state": "DE", "filing_type": "UCC-1",
            "filing_date": "2020-06-15", "lapse_date": "2025-06-15",
            "debtor_name": "Ironwood Manufacturing LLC",
            "debtor_address": "1313 North Market Street, Wilmington, DE 19801",
            "debtor_ein": "51-2234891",
            "secured_party": "PNC Business Credit",
            "secured_party_address": "300 Fifth Avenue, Pittsburgh, PA 15222",
            "collateral": "All machinery, equipment, tooling, and dies located at manufacturing facilities in PA and OH",
            "status": "active",
            "amendments": [
                {"number": "DE-2023-AMD-002", "date": "2023-05-30", "type": "collateral_change",
                 "description": "Added inventory and raw materials to collateral description"},
            ],
        },
        "DE-2024-0034567": {
            "filing_number": "DE-2024-0034567", "state": "DE", "filing_type": "UCC-1",
            "filing_date": "2024-02-01", "lapse_date": "2029-02-01",
            "debtor_name": "Ironwood Mfg LLC",
            "debtor_address": "1313 North Market Street, Wilmington, DE 19801",
            "debtor_ein": "51-2234891",
            "secured_party": "TD Bank Commercial Lending",
            "secured_party_address": "1 Portland Square, Portland, ME 04101",
            "collateral": "Accounts receivable and all rights to payment arising from the sale of manufactured goods",
            "status": "active",
            "amendments": [],
        },
        "DE-2019-0042198": {
            "filing_number": "DE-2019-0042198", "state": "DE", "filing_type": "UCC-1",
            "filing_date": "2019-11-10", "lapse_date": "2024-11-10",
            "debtor_name": "Sterling & Pratt Consulting Group Inc",
            "debtor_address": "500 Delaware Avenue, Suite 1200, Wilmington, DE 19801",
            "debtor_ein": "51-3391827",
            "secured_party": "First Republic Bank",
            "secured_party_address": "111 Pine Street, San Francisco, CA 94111",
            "collateral": "All assets",
            "status": "lapsed",
            "amendments": [],
        },
        "DE-2023-0221847": {
            "filing_number": "DE-2023-0221847", "state": "DE", "filing_type": "UCC-1",
            "filing_date": "2023-11-20", "lapse_date": "2028-11-20",
            "debtor_name": "Helix Biotech Partners LP",
            "debtor_address": "1209 Orange Street, Wilmington, DE 19801",
            "debtor_ein": "13-7756123",
            "secured_party": "Hercules Capital Inc",
            "secured_party_address": "400 Hamilton Avenue, Suite 310, Palo Alto, CA 94301",
            "collateral": "All tangible and intangible assets, including without limitation accounts, equipment, inventory, intellectual property, and investment property; provided however that the Collateral shall not include any Excluded Property as defined in the Loan Agreement dated November 15, 2023",
            "status": "active",
            "amendments": [],
        },
        "DE-2024-0045123": {
            "filing_number": "DE-2024-0045123", "state": "DE", "filing_type": "UCC-3",
            "filing_date": "2024-03-15", "lapse_date": None,
            "debtor_name": "Sterling & Pratt Consulting Group Inc",
            "debtor_address": "500 Delaware Avenue, Suite 1200, Wilmington, DE 19801",
            "debtor_ein": "51-3391827",
            "secured_party": "First Republic Bank (acquired by JPMorgan Chase)",
            "secured_party_address": "383 Madison Avenue, New York, NY 10179",
            "collateral": "Full termination of filing DE-2019-0042198",
            "status": "terminated",
            "amendments": [],
            "related_filing": "DE-2019-0042198",
        },
        "DE-2023-0301928": {
            "filing_number": "DE-2023-0301928", "state": "DE", "filing_type": "UCC-1",
            "filing_date": "2023-12-10", "lapse_date": "2028-12-10",
            "debtor_name": "Greenfield Organics Inc",
            "debtor_address": "1209 Orange Street, Wilmington, DE 19801",
            "debtor_ein": "13-5529843",
            "secured_party": "Farm Credit East ACA",
            "secured_party_address": "240 South Road, Enfield, CT 06082",
            "collateral": "Crops, farm products, and agricultural supplies; accounts receivable arising from the sale of organic produce",
            "status": "active",
            "amendments": [],
        },
        "DE-2024-0058291": {
            "filing_number": "DE-2024-0058291", "state": "DE", "filing_type": "UCC-1",
            "filing_date": "2024-04-18", "lapse_date": "2029-04-18",
            "debtor_name": "Pinnacle Systems Intl Inc",
            "debtor_address": "1209 Orange Street, Wilmington, DE 19801",
            "debtor_ein": "95-7712034",
            "secured_party": "Western Technology Investment",
            "secured_party_address": "2010 N First Street, Suite 310, San Jose, CA 95131",
            "collateral": "All assets of the Debtor excluding any real property interests",
            "status": "active",
            "amendments": [],
        },
    },

    # -----------------------------------------------------------------------
    # CALIFORNIA (11 filings)
    # -----------------------------------------------------------------------
    "CA": {
        "CA-2023-0847291": {
            "filing_number": "CA-2023-0847291", "state": "CA", "filing_type": "UCC-1",
            "filing_date": "2023-03-15", "lapse_date": "2028-03-15",
            "debtor_name": "Acme Corp",
            "debtor_address": "1200 Industrial Blvd, Suite 400, San Jose, CA 95112",
            "debtor_ein": "94-3829471",
            "secured_party": "Pacific Commerce Bank",
            "secured_party_address": "3478 Buskirk Avenue, Pleasant Hill, CA 94523",
            "collateral": "All inventory, equipment, accounts receivable, and general intangibles",
            "status": "active",
            "amendments": [],
        },
        "CA-2024-0112834": {
            "filing_number": "CA-2024-0112834", "state": "CA", "filing_type": "UCC-1",
            "filing_date": "2024-01-22", "lapse_date": "2029-01-22",
            "debtor_name": "ACME CORPORATION",
            "debtor_address": "1200 Industrial Blvd, Suite 400, San Jose, CA 95112",
            "debtor_ein": "94-3829471",
            "secured_party": "Western Capital Lending LLC",
            "secured_party_address": "600 Montgomery Street, Suite 1100, San Francisco, CA 94111",
            "collateral": "Equipment and fixtures located at 1200 Industrial Blvd, San Jose, CA",
            "status": "active",
            "amendments": [],
        },
        "CA-2022-0553192": {
            "filing_number": "CA-2022-0553192", "state": "CA", "filing_type": "UCC-1",
            "filing_date": "2022-08-10", "lapse_date": "2027-08-10",
            "debtor_name": "Pinnacle Systems International",
            "debtor_address": "8900 Gateway Drive, Los Angeles, CA 90045",
            "debtor_ein": "95-7712034",
            "secured_party": "First National Business Credit",
            "secured_party_address": "155 North Wacker Drive, Suite 2700, Chicago, IL 60606",
            "collateral": "All assets including accounts, chattel paper, equipment, general intangibles, instruments, inventory; together with all additions, accessions, and proceeds",
            "status": "active",
            "amendments": [
                {"number": "CA-2023-AMD-001", "date": "2023-06-01", "type": "collateral_change",
                 "description": "Added intellectual property (patents and trademarks) as additional collateral"},
            ],
        },
        "CA-2021-0289451": {
            "filing_number": "CA-2021-0289451", "state": "CA", "filing_type": "UCC-1",
            "filing_date": "2021-05-20", "lapse_date": "2026-05-20",
            "debtor_name": "Acme Corp dba AcmeTech Solutions",
            "debtor_address": "1200 Industrial Blvd, Suite 400, San Jose, CA 95112",
            "debtor_ein": "94-3829471",
            "secured_party": "Silicon Valley Equipment Finance",
            "secured_party_address": "2570 North First Street, Suite 200, San Jose, CA 95131",
            "collateral": "Specific equipment: CNC machinery serial numbers CMX-4400, CMX-4401, CMX-4402 and all replacements and proceeds thereof",
            "status": "active",
            "amendments": [],
        },
        "CA-2023-0991204": {
            "filing_number": "CA-2023-0991204", "state": "CA", "filing_type": "UCC-1",
            "filing_date": "2023-11-05", "lapse_date": "2028-11-05",
            "debtor_name": "Acme Holdings LLC",
            "debtor_address": "2500 Venture Parkway, Palo Alto, CA 94301",
            "debtor_ein": "94-5501287",
            "secured_party": "Bay Area Commercial Lending",
            "secured_party_address": "1901 Harrison Street, Oakland, CA 94612",
            "collateral": "Membership interests and equity in subsidiaries; all distributions and proceeds thereof",
            "status": "active",
            "amendments": [],
        },
        "CA-2024-0156782": {
            "filing_number": "CA-2024-0156782", "state": "CA", "filing_type": "UCC-1",
            "filing_date": "2024-03-01", "lapse_date": "2029-03-01",
            "debtor_name": "Cascade Tech Corp",
            "debtor_address": "525 University Avenue, Palo Alto, CA 94301",
            "debtor_ein": "13-9923847",
            "secured_party": "Trinity Capital Inc",
            "secured_party_address": "1 N First Street, Suite 302, Phoenix, AZ 85004",
            "collateral": "Equipment and software systems; all proceeds and products thereof",
            "status": "active",
            "amendments": [],
        },
        "CA-2020-0712934": {
            "filing_number": "CA-2020-0712934", "state": "CA", "filing_type": "UCC-1",
            "filing_date": "2020-02-14", "lapse_date": "2025-02-14",
            "debtor_name": "Solaris Energy Solutions Inc",
            "debtor_address": "42000 Christy Street, Fremont, CA 94538",
            "debtor_ein": "94-7781234",
            "secured_party": "US Bank Equipment Finance",
            "secured_party_address": "800 Nicollet Mall, Minneapolis, MN 55402",
            "collateral": "Solar panel arrays, inverters, and battery storage systems installed at customer sites per Schedule B",
            "status": "active",
            "amendments": [
                {"number": "CA-2023-AMD-002", "date": "2023-01-20", "type": "continuation",
                 "description": "Continuation statement filed — extends lapse date to 2030-02-14"},
            ],
        },
        "CA-2023-0834129": {
            "filing_number": "CA-2023-0834129", "state": "CA", "filing_type": "UCC-1",
            "filing_date": "2023-06-18", "lapse_date": "2028-06-18",
            "debtor_name": "Solaris Energy Solutions",
            "debtor_address": "42000 Christy Street, Fremont, CA 94538",
            "debtor_ein": "94-7781234",
            "secured_party": "Green Energy Capital Partners",
            "secured_party_address": "100 California Street, Suite 500, San Francisco, CA 94111",
            "collateral": "Power purchase agreements (PPAs), renewable energy certificates (RECs), and all payment rights arising thereunder",
            "status": "active",
            "amendments": [],
        },
        "CA-2019-0398172": {
            "filing_number": "CA-2019-0398172", "state": "CA", "filing_type": "UCC-1",
            "filing_date": "2019-07-01", "lapse_date": "2024-07-01",
            "debtor_name": "Pacific Rim Trading Co",
            "debtor_address": "1 Ferry Building, Suite 200, San Francisco, CA 94105",
            "debtor_ein": "94-6653218",
            "secured_party": "East West Bank",
            "secured_party_address": "135 N Los Robles Avenue, Pasadena, CA 91101",
            "collateral": "Import/export inventory, warehouse receipts, bills of lading, and all proceeds",
            "status": "lapsed",
            "amendments": [],
        },
        "CA-2024-0201983": {
            "filing_number": "CA-2024-0201983", "state": "CA", "filing_type": "UCC-1",
            "filing_date": "2024-04-10", "lapse_date": "2029-04-10",
            "debtor_name": "Pacific Rim Trading Company LLC",
            "debtor_address": "1 Ferry Building, Suite 200, San Francisco, CA 94105",
            "debtor_ein": "94-6653218",
            "secured_party": "Cathay Bank",
            "secured_party_address": "777 North Broadway, Los Angeles, CA 90012",
            "collateral": "All assets including inventory, accounts receivable, and equipment",
            "status": "active",
            "amendments": [],
        },
        "CA-2023-0678492": {
            "filing_number": "CA-2023-0678492", "state": "CA", "filing_type": "UCC-3",
            "filing_date": "2023-09-15", "lapse_date": None,
            "debtor_name": "Pacific Rim Trading Co",
            "debtor_address": "1 Ferry Building, Suite 200, San Francisco, CA 94105",
            "debtor_ein": "94-6653218",
            "secured_party": "East West Bank",
            "secured_party_address": "135 N Los Robles Avenue, Pasadena, CA 91101",
            "collateral": "Full termination of financing statement CA-2019-0398172",
            "status": "terminated",
            "amendments": [],
            "related_filing": "CA-2019-0398172",
        },
    },

    # -----------------------------------------------------------------------
    # TEXAS (10 filings)
    # -----------------------------------------------------------------------
    "TX": {
        "TX-2022-1847592": {
            "filing_number": "TX-2022-1847592", "state": "TX", "filing_type": "UCC-1",
            "filing_date": "2022-11-03", "lapse_date": "2027-11-03",
            "debtor_name": "Acme Corp",
            "debtor_address": "5600 Research Park Drive, Austin, TX 78759",
            "debtor_ein": "94-3829471",
            "secured_party": "Lone Star Business Credit",
            "secured_party_address": "500 West 5th Street, Suite 1200, Austin, TX 78701",
            "collateral": "All inventory, accounts receivable, and equipment at Austin facility",
            "status": "active",
            "amendments": [
                {"number": "TX-2023-AMD-001", "date": "2023-09-15", "type": "continuation",
                 "description": "Five-year continuation statement filed — extends lapse date to 2032-11-03"},
            ],
        },
        "TX-2024-0229183": {
            "filing_number": "TX-2024-0229183", "state": "TX", "filing_type": "UCC-1",
            "filing_date": "2024-03-10", "lapse_date": "2029-03-10",
            "debtor_name": "ACME CORP",
            "debtor_address": "5600 Research Park Drive, Austin, TX 78759",
            "debtor_ein": "94-3829471",
            "secured_party": "Texas Regional Bank",
            "secured_party_address": "221 West 6th Street, Austin, TX 78701",
            "collateral": "Revolving line of credit secured by accounts receivable",
            "status": "active",
            "amendments": [],
        },
        "TX-2023-1102847": {
            "filing_number": "TX-2023-1102847", "state": "TX", "filing_type": "UCC-1",
            "filing_date": "2023-04-22", "lapse_date": "2028-04-22",
            "debtor_name": "Pinnacle Systems International Inc",
            "debtor_address": "7200 MoPac Expressway, Suite 300, Austin, TX 78731",
            "debtor_ein": "95-7712034",
            "secured_party": "Capital One Commercial Banking",
            "secured_party_address": "1680 Capital One Drive, McLean, VA 22102",
            "collateral": "All assets",
            "status": "active",
            "amendments": [],
        },
        "TX-2023-1234567": {
            "filing_number": "TX-2023-1234567", "state": "TX", "filing_type": "UCC-1",
            "filing_date": "2023-07-01", "lapse_date": "2028-07-01",
            "debtor_name": "Ironwood Manufacturing",
            "debtor_address": "2200 South Lamar Blvd, Suite 300, Austin, TX 78704",
            "debtor_ein": "51-2234891",
            "secured_party": "Amegy Bank of Texas",
            "secured_party_address": "4400 Post Oak Parkway, Houston, TX 77027",
            "collateral": "Equipment and machinery at Texas manufacturing facility; raw materials and work-in-process inventory",
            "status": "active",
            "amendments": [],
        },
        "TX-2021-0891234": {
            "filing_number": "TX-2021-0891234", "state": "TX", "filing_type": "UCC-1",
            "filing_date": "2021-02-15", "lapse_date": "2026-02-15",
            "debtor_name": "Rio Grande Agricultural Supply Co",
            "debtor_address": "1500 South Congress Avenue, Austin, TX 78704",
            "debtor_ein": "74-2298134",
            "secured_party": "Farm Credit Bank of Texas",
            "secured_party_address": "4801 Plaza on the Lake Drive, Austin, TX 78746",
            "collateral": "Farm products, crops, livestock, and agricultural equipment; all government program payments and subsidies",
            "status": "active",
            "amendments": [],
        },
        "TX-2024-0312456": {
            "filing_number": "TX-2024-0312456", "state": "TX", "filing_type": "UCC-1",
            "filing_date": "2024-04-25", "lapse_date": "2029-04-25",
            "debtor_name": "Rio Grande Ag Supply",
            "debtor_address": "1500 South Congress Avenue, Austin, TX 78704",
            "debtor_ein": "74-2298134",
            "secured_party": "John Deere Financial",
            "secured_party_address": "6400 NW 86th Street, Johnston, IA 50131",
            "collateral": "Specific equipment: John Deere tractors model 8R 410 (S/N JD8R410-2847, JD8R410-2848); combine harvester model S780 (S/N JDS780-1192)",
            "status": "active",
            "amendments": [],
        },
        "TX-2022-0567891": {
            "filing_number": "TX-2022-0567891", "state": "TX", "filing_type": "UCC-1",
            "filing_date": "2022-05-18", "lapse_date": "2027-05-18",
            "debtor_name": "Gulf Coast Energy Partners LP",
            "debtor_address": "1000 Louisiana Street, Suite 4800, Houston, TX 77002",
            "debtor_ein": "76-0512389",
            "secured_party": "Macquarie Energy Capital",
            "secured_party_address": "125 West 55th Street, New York, NY 10019",
            "collateral": "Oil and gas leases, mineral rights, wellhead equipment, and all hydrocarbons produced therefrom; pipeline rights-of-way",
            "status": "active",
            "amendments": [],
        },
        "TX-2023-0789123": {
            "filing_number": "TX-2023-0789123", "state": "TX", "filing_type": "UCC-1",
            "filing_date": "2023-09-10", "lapse_date": "2028-09-10",
            "debtor_name": "Gulf Coast Energy Ptnrs",
            "debtor_address": "1000 Louisiana Street, Suite 4800, Houston, TX 77002",
            "debtor_ein": "76-0512389",
            "secured_party": "Barclays Energy Trading",
            "secured_party_address": "745 Seventh Avenue, New York, NY 10019",
            "collateral": "Commodity trading accounts, hedging contracts, and all margin deposits related thereto",
            "status": "active",
            "amendments": [],
        },
        "TX-2020-0445678": {
            "filing_number": "TX-2020-0445678", "state": "TX", "filing_type": "UCC-1",
            "filing_date": "2020-08-30", "lapse_date": "2025-08-30",
            "debtor_name": "Metro Construction Holdings Inc",
            "debtor_address": "1100 Congress Avenue, Suite 400, Austin, TX 78701",
            "debtor_ein": "13-6672190",
            "secured_party": "Frost Bank Commercial Lending",
            "secured_party_address": "100 W Houston Street, San Antonio, TX 78205",
            "collateral": "Construction vehicles, earthmoving equipment, and cranes as listed in Equipment Schedule dated August 28, 2020",
            "status": "active",
            "amendments": [],
        },
        "TX-2024-0401289": {
            "filing_number": "TX-2024-0401289", "state": "TX", "filing_type": "UCC-3",
            "filing_date": "2024-05-01", "lapse_date": None,
            "debtor_name": "Metro Construction Holdings Inc",
            "debtor_address": "1100 Congress Avenue, Suite 400, Austin, TX 78701",
            "debtor_ein": "13-6672190",
            "secured_party": "Frost Bank Commercial Lending",
            "secured_party_address": "100 W Houston Street, San Antonio, TX 78205",
            "collateral": "Amendment: release of cranes from collateral per payoff of Term Loan B",
            "status": "amendment",
            "amendments": [],
            "related_filing": "TX-2020-0445678",
        },
    },

    # -----------------------------------------------------------------------
    # FLORIDA (10 filings)
    # -----------------------------------------------------------------------
    "FL": {
        "FL-2023-0291847": {
            "filing_number": "FL-2023-0291847", "state": "FL", "filing_type": "UCC-1",
            "filing_date": "2023-02-28", "lapse_date": "2028-02-28",
            "debtor_name": "Acme Corporation",
            "debtor_address": "200 South Biscayne Blvd, Suite 3200, Miami, FL 33131",
            "debtor_ein": "94-3829471",
            "secured_party": "Regions Bank Commercial Banking",
            "secured_party_address": "1900 Fifth Avenue North, Birmingham, AL 35203",
            "collateral": "All accounts receivable, inventory, and equipment at Florida operations",
            "status": "active",
            "amendments": [],
        },
        "FL-2024-0045192": {
            "filing_number": "FL-2024-0045192", "state": "FL", "filing_type": "UCC-1",
            "filing_date": "2024-01-15", "lapse_date": "2029-01-15",
            "debtor_name": "Pinnacle Systems International",
            "debtor_address": "1 SE 3rd Avenue, Suite 2800, Miami, FL 33131",
            "debtor_ein": "95-7712034",
            "secured_party": "BankUnited Commercial Finance",
            "secured_party_address": "14817 Oak Lane, Miami Lakes, FL 33016",
            "collateral": "Equipment, software licenses, and related technology assets at Miami data center",
            "status": "active",
            "amendments": [],
        },
        "FL-2022-0178934": {
            "filing_number": "FL-2022-0178934", "state": "FL", "filing_type": "UCC-1",
            "filing_date": "2022-09-12", "lapse_date": "2027-09-12",
            "debtor_name": "Suncoast Marine Ventures LLC",
            "debtor_address": "401 East Las Olas Blvd, Suite 1400, Fort Lauderdale, FL 33301",
            "debtor_ein": "59-3847291",
            "secured_party": "CIT Marine Finance",
            "secured_party_address": "1 CIT Drive, Livingston, NJ 07039",
            "collateral": "Marine vessels: MY Ocean Breeze (USCG 1298345), MY Coral Reef (USCG 1298346); all equipment, fittings, and insurance proceeds",
            "status": "active",
            "amendments": [],
        },
        "FL-2023-0334521": {
            "filing_number": "FL-2023-0334521", "state": "FL", "filing_type": "UCC-1",
            "filing_date": "2023-05-20", "lapse_date": "2028-05-20",
            "debtor_name": "Suncoast Marine Ventures",
            "debtor_address": "401 East Las Olas Blvd, Suite 1400, Fort Lauderdale, FL 33301",
            "debtor_ein": "59-3847291",
            "secured_party": "SunTrust Robinson Humphrey (now Truist Securities)",
            "secured_party_address": "303 Peachtree Street NE, Suite 4000, Atlanta, GA 30308",
            "collateral": "Charter agreements, accounts receivable from vessel operations, and all insurance proceeds",
            "status": "active",
            "amendments": [],
        },
        "FL-2021-0512389": {
            "filing_number": "FL-2021-0512389", "state": "FL", "filing_type": "UCC-1",
            "filing_date": "2021-06-30", "lapse_date": "2026-06-30",
            "debtor_name": "Greenfield Organics",
            "debtor_address": "2600 South Bayshore Drive, Suite 700, Miami, FL 33133",
            "debtor_ein": "13-5529843",
            "secured_party": "CenterState Bank (now South State Bank)",
            "secured_party_address": "1101 First Street South, Winter Haven, FL 33880",
            "collateral": "Inventory of organic food products, cold storage equipment, and delivery vehicles at Florida distribution center",
            "status": "active",
            "amendments": [],
        },
        "FL-2024-0089234": {
            "filing_number": "FL-2024-0089234", "state": "FL", "filing_type": "UCC-1",
            "filing_date": "2024-02-20", "lapse_date": "2029-02-20",
            "debtor_name": "Everglades Development Corp",
            "debtor_address": "333 SE 2nd Avenue, Suite 4400, Miami, FL 33131",
            "debtor_ein": "59-4128397",
            "secured_party": "Centennial Bank",
            "secured_party_address": "220 Market Street, Melbourne, AR 72556",
            "collateral": "Real property development rights, construction permits, and all contract rights related to the Bayshore Towers project",
            "status": "active",
            "amendments": [],
        },
        "FL-2023-0467891": {
            "filing_number": "FL-2023-0467891", "state": "FL", "filing_type": "UCC-1",
            "filing_date": "2023-08-05", "lapse_date": "2028-08-05",
            "debtor_name": "Everglades Development Corporation",
            "debtor_address": "333 SE 2nd Avenue, Suite 4400, Miami, FL 33131",
            "debtor_ein": "59-4128397",
            "secured_party": "Synovus Bank",
            "secured_party_address": "1111 Bay Avenue, Suite 500, Columbus, GA 31901",
            "collateral": "Construction equipment, building materials inventory, and accounts receivable from construction contracts",
            "status": "active",
            "amendments": [],
        },
        "FL-2020-0234567": {
            "filing_number": "FL-2020-0234567", "state": "FL", "filing_type": "UCC-1",
            "filing_date": "2020-04-15", "lapse_date": "2025-04-15",
            "debtor_name": "Vertex Capital Advisors",
            "debtor_address": "200 South Biscayne Blvd, Suite 1500, Miami, FL 33131",
            "debtor_ein": "13-8847291",
            "secured_party": "UBS Financial Services",
            "secured_party_address": "1285 Avenue of the Americas, New York, NY 10019",
            "collateral": "Investment securities, margin accounts, and all financial assets held in UBS custody accounts",
            "status": "active",
            "amendments": [
                {"number": "FL-2023-AMD-001", "date": "2023-04-10", "type": "continuation",
                 "description": "Continuation statement filed — extends lapse date to 2030-04-15"},
            ],
        },
        "FL-2024-0112345": {
            "filing_number": "FL-2024-0112345", "state": "FL", "filing_type": "UCC-1",
            "filing_date": "2024-03-05", "lapse_date": "2029-03-05",
            "debtor_name": "Trident Logistics Group",
            "debtor_address": "5201 Blue Lagoon Drive, Suite 900, Miami, FL 33126",
            "debtor_ein": "51-0482193",
            "secured_party": "GATX Financial Corporation",
            "secured_party_address": "222 West Adams Street, Chicago, IL 60606",
            "collateral": "Intermodal containers (quantity: 200), chassis, and tracking/telematics equipment installed thereon",
            "status": "active",
            "amendments": [],
        },
        "FL-2023-0589012": {
            "filing_number": "FL-2023-0589012", "state": "FL", "filing_type": "UCC-1",
            "filing_date": "2023-10-22", "lapse_date": "2028-10-22",
            "debtor_name": "Sterling Pratt Consulting",
            "debtor_address": "100 North Tampa Street, Suite 3700, Tampa, FL 33602",
            "debtor_ein": "51-3391827",
            "secured_party": "Valley National Bank",
            "secured_party_address": "1455 Valley Road, Wayne, NJ 07470",
            "collateral": "Accounts receivable from consulting engagements, work-in-progress, and all payment rights under government contracts",
            "status": "active",
            "amendments": [],
        },
    },
}

# ---------------------------------------------------------------------------
# Business Registry — 15 entities
# ---------------------------------------------------------------------------
BUSINESS_REGISTRY = {
    "94-3829471": {
        "ein": "94-3829471", "legal_name": "Acme Corporation",
        "dba_names": ["Acme Corp", "AcmeTech Solutions", "Acme Industrial"],
        "entity_type": "Corporation", "state_of_incorporation": "DE",
        "incorporation_date": "2005-03-22", "status": "active",
        "registered_agent": "Corporation Service Company, 251 Little Falls Drive, Wilmington, DE 19808",
        "officers": [
            {"name": "Robert Chen", "title": "CEO", "since": "2018-01-01"},
            {"name": "Sarah Martinez", "title": "CFO", "since": "2020-06-15"},
            {"name": "David Kim", "title": "COO", "since": "2019-09-01"},
        ],
        "addresses": {
            "headquarters": "1200 Industrial Blvd, Suite 400, San Jose, CA 95112",
            "registered": "1209 Orange Street, Wilmington, DE 19801",
            "branches": [
                "100 Commerce Center Drive, Reno, NV 89501",
                "5600 Research Park Drive, Austin, TX 78759",
                "350 Fifth Avenue, Suite 5100, New York, NY 10118",
                "200 South Biscayne Blvd, Suite 3200, Miami, FL 33131",
            ],
        },
        "annual_revenue_range": "$50M-$100M",
        "employee_count_range": "200-500",
        "naics_codes": ["333249", "423830"],
        "name_history": [
            {"name": "Acme Corp", "effective_date": "2005-03-22", "end_date": "2022-01-15"},
            {"name": "Acme Corporation", "effective_date": "2022-01-15", "end_date": None},
        ],
    },
    "95-7712034": {
        "ein": "95-7712034", "legal_name": "Pinnacle Systems International Inc",
        "dba_names": ["Pinnacle Systems", "PSI Technology", "Pinnacle Systems Intl"],
        "entity_type": "Corporation", "state_of_incorporation": "DE",
        "incorporation_date": "2010-08-11", "status": "active",
        "registered_agent": "National Registered Agents Inc, 160 Greentree Drive, Dover, DE 19904",
        "officers": [
            {"name": "Marcus Wong", "title": "CEO", "since": "2015-03-01"},
            {"name": "Elena Petrov", "title": "CTO", "since": "2016-11-01"},
        ],
        "addresses": {
            "headquarters": "8900 Gateway Drive, Los Angeles, CA 90045",
            "registered": "160 Greentree Drive, Dover, DE 19904",
            "branches": [
                "4400 South Virginia Street, Reno, NV 89502",
                "7200 MoPac Expressway, Suite 300, Austin, TX 78731",
                "One Penn Plaza, Suite 2200, New York, NY 10119",
                "1 SE 3rd Avenue, Suite 2800, Miami, FL 33131",
            ],
        },
        "annual_revenue_range": "$25M-$50M",
        "employee_count_range": "100-200",
        "naics_codes": ["541512", "334111"],
        "name_history": [
            {"name": "Pinnacle Systems International", "effective_date": "2010-08-11", "end_date": "2019-04-01"},
            {"name": "Pinnacle Systems International Inc", "effective_date": "2019-04-01", "end_date": None},
        ],
    },
    "94-5501287": {
        "ein": "94-5501287", "legal_name": "Acme Holdings LLC",
        "dba_names": [], "entity_type": "LLC", "state_of_incorporation": "DE",
        "incorporation_date": "2018-07-10", "status": "active",
        "registered_agent": "Corporation Service Company, 251 Little Falls Drive, Wilmington, DE 19808",
        "officers": [{"name": "Robert Chen", "title": "Managing Member", "since": "2018-07-10"}],
        "addresses": {
            "headquarters": "2500 Venture Parkway, Palo Alto, CA 94301",
            "registered": "1209 Orange Street, Wilmington, DE 19801",
        },
        "annual_revenue_range": "Not reported (holding company)",
        "employee_count_range": "1-10",
        "naics_codes": ["551112"],
        "name_history": [],
        "notes": "Parent holding company of Acme Corporation (EIN 94-3829471). Same CEO (Robert Chen).",
    },
    "51-0482193": {
        "ein": "51-0482193", "legal_name": "Trident Logistics Group LLC",
        "dba_names": ["Trident Freight", "Pinnacle Transport Services"],
        "entity_type": "LLC", "state_of_incorporation": "DE",
        "incorporation_date": "2017-02-14", "status": "active",
        "registered_agent": "Incorp Services Inc, 1201 Orange Street, Wilmington, DE 19801",
        "officers": [{"name": "James Callahan", "title": "Managing Member", "since": "2017-02-14"}],
        "addresses": {
            "headquarters": "300 Delaware Avenue, Suite 900, Wilmington, DE 19801",
            "branches": ["5201 Blue Lagoon Drive, Suite 900, Miami, FL 33126"],
        },
        "annual_revenue_range": "$10M-$25M",
        "employee_count_range": "50-100",
        "naics_codes": ["484110", "484121"],
        "name_history": [
            {"name": "Pinnacle Transport Services LLC", "effective_date": "2017-02-14", "end_date": "2022-09-01"},
            {"name": "Trident Logistics Group LLC", "effective_date": "2022-09-01", "end_date": None},
        ],
        "notes": "Formerly 'Pinnacle Transport Services' — NO relation to 'Pinnacle Systems International' despite similar naming.",
    },
    "13-5529843": {
        "ein": "13-5529843", "legal_name": "Greenfield Organics Inc",
        "dba_names": ["Greenfield Organic Foods", "GF Organics"],
        "entity_type": "Corporation", "state_of_incorporation": "DE",
        "incorporation_date": "2015-01-20", "status": "active",
        "registered_agent": "Harvard Business Services Inc, 16192 Coastal Hwy, Lewes, DE 19958",
        "officers": [
            {"name": "Patricia Huang", "title": "CEO", "since": "2015-01-20"},
            {"name": "Michael Torres", "title": "VP Operations", "since": "2019-03-01"},
        ],
        "addresses": {
            "headquarters": "88 Pine Street, Suite 1200, New York, NY 10005",
            "registered": "1209 Orange Street, Wilmington, DE 19801",
            "branches": ["2600 South Bayshore Drive, Suite 700, Miami, FL 33133"],
        },
        "annual_revenue_range": "$10M-$25M",
        "employee_count_range": "50-100",
        "naics_codes": ["311999", "424490"],
        "name_history": [],
    },
    "13-8847291": {
        "ein": "13-8847291", "legal_name": "Vertex Capital Advisors LLC",
        "dba_names": ["Vertex Capital", "VCA Partners"],
        "entity_type": "LLC", "state_of_incorporation": "DE",
        "incorporation_date": "2012-04-15", "status": "active",
        "registered_agent": "The Corporation Trust Company, 1209 Orange Street, Wilmington, DE 19801",
        "officers": [
            {"name": "Jonathan Blake", "title": "Managing Partner", "since": "2012-04-15"},
            {"name": "Rebecca Liu", "title": "Chief Investment Officer", "since": "2017-09-01"},
        ],
        "addresses": {
            "headquarters": "200 Park Avenue, Suite 3100, New York, NY 10166",
            "registered": "1201 North Market Street, Suite 1800, Wilmington, DE 19801",
            "branches": ["200 South Biscayne Blvd, Suite 1500, Miami, FL 33131"],
        },
        "annual_revenue_range": "$5M-$10M",
        "employee_count_range": "10-50",
        "naics_codes": ["523920", "523910"],
        "name_history": [],
    },
    "13-6672190": {
        "ein": "13-6672190", "legal_name": "Metro Construction Holdings Inc",
        "dba_names": ["Metro Construction", "MCH Builders"],
        "entity_type": "Corporation", "state_of_incorporation": "NY",
        "incorporation_date": "2008-11-05", "status": "active",
        "registered_agent": "CT Corporation System, 28 Liberty Street, New York, NY 10005",
        "officers": [
            {"name": "Anthony Russo", "title": "CEO", "since": "2008-11-05"},
            {"name": "Maria Garcia", "title": "CFO", "since": "2015-06-01"},
        ],
        "addresses": {
            "headquarters": "450 Lexington Avenue, Suite 1800, New York, NY 10017",
            "branches": ["1100 Congress Avenue, Suite 400, Austin, TX 78701"],
        },
        "annual_revenue_range": "$25M-$50M",
        "employee_count_range": "100-200",
        "naics_codes": ["236220", "237310"],
        "name_history": [],
    },
    "13-9923847": {
        "ein": "13-9923847", "legal_name": "Cascade Technologies Corporation",
        "dba_names": ["Cascade Tech", "Cascade Tech Corp"],
        "entity_type": "Corporation", "state_of_incorporation": "DE",
        "incorporation_date": "2019-06-01", "status": "active",
        "registered_agent": "Registered Agents Inc, 838 Walker Road, Suite 21-2, Dover, DE 19904",
        "officers": [
            {"name": "Andrew Park", "title": "CEO", "since": "2019-06-01"},
            {"name": "Lisa Nakamura", "title": "CTO", "since": "2019-06-01"},
        ],
        "addresses": {
            "headquarters": "525 University Avenue, Palo Alto, CA 94301",
            "registered": "1209 Orange Street, Wilmington, DE 19801",
            "branches": ["100 Wall Street, Suite 800, New York, NY 10005"],
        },
        "annual_revenue_range": "$5M-$10M",
        "employee_count_range": "25-50",
        "naics_codes": ["511210", "541511"],
        "name_history": [
            {"name": "Cascade Technologies Corp", "effective_date": "2019-06-01", "end_date": "2023-01-15"},
            {"name": "Cascade Technologies Corporation", "effective_date": "2023-01-15", "end_date": None},
        ],
    },
    "13-4418927": {
        "ein": "13-4418927", "legal_name": "Apex Marine Services LLC",
        "dba_names": ["Apex Marine", "AMS Shipping"],
        "entity_type": "LLC", "state_of_incorporation": "NY",
        "incorporation_date": "2016-08-22", "status": "active",
        "registered_agent": "LegalInc Corporate Services Inc, 1967 Wehrle Drive, Buffalo, NY 14221",
        "officers": [
            {"name": "Dimitri Konstantinos", "title": "Managing Member", "since": "2016-08-22"},
        ],
        "addresses": {
            "headquarters": "17 Battery Place, Suite 600, New York, NY 10004",
        },
        "annual_revenue_range": "$10M-$25M",
        "employee_count_range": "25-50",
        "naics_codes": ["483111", "488320"],
        "name_history": [],
    },
    "13-7756123": {
        "ein": "13-7756123", "legal_name": "Helix Biotech Partners LP",
        "dba_names": ["Helix Bio", "Helix Pharma"],
        "entity_type": "Limited Partnership", "state_of_incorporation": "DE",
        "incorporation_date": "2020-02-01", "status": "active",
        "registered_agent": "The Corporation Trust Company, 1209 Orange Street, Wilmington, DE 19801",
        "officers": [
            {"name": "Dr. Sophia Andreou", "title": "General Partner", "since": "2020-02-01"},
            {"name": "Kevin Walsh", "title": "CFO", "since": "2021-05-15"},
        ],
        "addresses": {
            "headquarters": "430 East 29th Street, Suite 14A, New York, NY 10016",
            "registered": "1209 Orange Street, Wilmington, DE 19801",
        },
        "annual_revenue_range": "$1M-$5M",
        "employee_count_range": "10-25",
        "naics_codes": ["325414", "541711"],
        "name_history": [],
    },
    "51-2234891": {
        "ein": "51-2234891", "legal_name": "Ironwood Manufacturing LLC",
        "dba_names": ["Ironwood Mfg", "Ironwood Manufacturing"],
        "entity_type": "LLC", "state_of_incorporation": "DE",
        "incorporation_date": "2013-09-10", "status": "active",
        "registered_agent": "Incorp Services Inc, 1201 Orange Street, Wilmington, DE 19801",
        "officers": [
            {"name": "Thomas O'Brien", "title": "CEO", "since": "2013-09-10"},
            {"name": "Janet Williams", "title": "VP Manufacturing", "since": "2018-01-01"},
        ],
        "addresses": {
            "headquarters": "1313 North Market Street, Wilmington, DE 19801",
            "branches": ["2200 South Lamar Blvd, Suite 300, Austin, TX 78704"],
        },
        "annual_revenue_range": "$10M-$25M",
        "employee_count_range": "50-100",
        "naics_codes": ["332710", "333517"],
        "name_history": [],
    },
    "51-3391827": {
        "ein": "51-3391827", "legal_name": "Sterling & Pratt Consulting Group Inc",
        "dba_names": ["Sterling Pratt", "Sterling Pratt Consulting", "S&P Consulting"],
        "entity_type": "Corporation", "state_of_incorporation": "DE",
        "incorporation_date": "2014-05-01", "status": "active",
        "registered_agent": "Harvard Business Services Inc, 16192 Coastal Hwy, Lewes, DE 19958",
        "officers": [
            {"name": "Victoria Sterling", "title": "CEO", "since": "2014-05-01"},
            {"name": "Harold Pratt", "title": "President", "since": "2014-05-01"},
        ],
        "addresses": {
            "headquarters": "500 Delaware Avenue, Suite 1200, Wilmington, DE 19801",
            "branches": ["100 North Tampa Street, Suite 3700, Tampa, FL 33602"],
        },
        "annual_revenue_range": "$5M-$10M",
        "employee_count_range": "25-50",
        "naics_codes": ["541611", "541612"],
        "name_history": [],
    },
    "94-7781234": {
        "ein": "94-7781234", "legal_name": "Solaris Energy Solutions Inc",
        "dba_names": ["Solaris Energy", "Solaris Solar"],
        "entity_type": "Corporation", "state_of_incorporation": "CA",
        "incorporation_date": "2016-03-15", "status": "active",
        "registered_agent": "Legalzoom.com Inc, 101 N Brand Blvd, Glendale, CA 91203",
        "officers": [
            {"name": "Raj Patel", "title": "CEO", "since": "2016-03-15"},
            {"name": "Jennifer Wu", "title": "COO", "since": "2020-01-15"},
        ],
        "addresses": {
            "headquarters": "42000 Christy Street, Fremont, CA 94538",
        },
        "annual_revenue_range": "$10M-$25M",
        "employee_count_range": "50-100",
        "naics_codes": ["221114", "238220"],
        "name_history": [],
    },
    "94-6653218": {
        "ein": "94-6653218", "legal_name": "Pacific Rim Trading Company LLC",
        "dba_names": ["Pacific Rim Trading", "Pacific Rim Trading Co", "PRT Co"],
        "entity_type": "LLC", "state_of_incorporation": "CA",
        "incorporation_date": "2011-10-20", "status": "active",
        "registered_agent": "Legalzoom.com Inc, 101 N Brand Blvd, Glendale, CA 91203",
        "officers": [
            {"name": "Henry Zhao", "title": "Managing Member", "since": "2011-10-20"},
        ],
        "addresses": {
            "headquarters": "1 Ferry Building, Suite 200, San Francisco, CA 94105",
        },
        "annual_revenue_range": "$5M-$10M",
        "employee_count_range": "10-25",
        "naics_codes": ["423990", "424990"],
        "name_history": [
            {"name": "Pacific Rim Trading Co", "effective_date": "2011-10-20", "end_date": "2023-06-01"},
            {"name": "Pacific Rim Trading Company LLC", "effective_date": "2023-06-01", "end_date": None},
        ],
    },
    "59-3847291": {
        "ein": "59-3847291", "legal_name": "Suncoast Marine Ventures LLC",
        "dba_names": ["Suncoast Marine", "Suncoast Charters"],
        "entity_type": "LLC", "state_of_incorporation": "FL",
        "incorporation_date": "2018-04-10", "status": "active",
        "registered_agent": "Registered Agent Solutions Inc, 2000 PGA Blvd, Suite 4440, Palm Beach Gardens, FL 33408",
        "officers": [
            {"name": "Carlos Rivera", "title": "Managing Member", "since": "2018-04-10"},
            {"name": "Sophie Blanchard", "title": "Operations Director", "since": "2020-08-01"},
        ],
        "addresses": {
            "headquarters": "401 East Las Olas Blvd, Suite 1400, Fort Lauderdale, FL 33301",
        },
        "annual_revenue_range": "$5M-$10M",
        "employee_count_range": "10-25",
        "naics_codes": ["713930", "487210"],
        "name_history": [],
    },
}

# Additional entities referenced in filings but not in primary registry
# (used for edge cases in entity resolution)
ADDITIONAL_ENTITIES = {
    "59-4128397": {
        "ein": "59-4128397", "legal_name": "Everglades Development Corporation",
        "dba_names": ["Everglades Development", "Everglades Dev Corp"],
        "entity_type": "Corporation", "state_of_incorporation": "FL",
        "status": "active",
    },
    "74-2298134": {
        "ein": "74-2298134", "legal_name": "Rio Grande Agricultural Supply Co",
        "dba_names": ["Rio Grande Ag Supply", "RGAS"],
        "entity_type": "Corporation", "state_of_incorporation": "TX",
        "status": "active",
    },
    "76-0512389": {
        "ein": "76-0512389", "legal_name": "Gulf Coast Energy Partners LP",
        "dba_names": ["Gulf Coast Energy", "Gulf Coast Energy Ptnrs", "GCEP"],
        "entity_type": "Limited Partnership", "state_of_incorporation": "TX",
        "status": "active",
    },
}


# ---------------------------------------------------------------------------
# Collateral Category Classification Reference
# ---------------------------------------------------------------------------
COLLATERAL_CATEGORIES = {
    "all_assets": {
        "description": "Blanket lien covering all assets of the debtor",
        "risk_level": "high",
        "keywords": ["all assets", "all tangible and intangible", "now owned or hereafter acquired"],
    },
    "accounts_receivable": {
        "description": "Rights to payment from sale of goods or services",
        "risk_level": "medium",
        "keywords": ["accounts receivable", "accounts", "rights to payment", "contract rights"],
    },
    "inventory": {
        "description": "Goods held for sale or lease, raw materials, work in progress",
        "risk_level": "medium",
        "keywords": ["inventory", "goods held for sale", "raw materials", "work-in-process"],
    },
    "equipment": {
        "description": "Tangible property used in business operations",
        "risk_level": "low",
        "keywords": ["equipment", "machinery", "fixtures", "furniture", "vehicles"],
    },
    "intellectual_property": {
        "description": "Patents, trademarks, copyrights, trade secrets",
        "risk_level": "high",
        "keywords": ["intellectual property", "patents", "trademarks", "copyrights", "trade secrets", "IP"],
    },
    "investment_property": {
        "description": "Securities, securities accounts, commodity contracts",
        "risk_level": "high",
        "keywords": ["investment property", "securities", "margin accounts", "financial assets"],
    },
    "specific_equipment": {
        "description": "Named or serial-numbered equipment items",
        "risk_level": "low",
        "keywords": ["serial number", "specific equipment", "VIN", "IMO"],
    },
    "real_property_related": {
        "description": "Fixtures, development rights, construction-related",
        "risk_level": "medium",
        "keywords": ["real property", "fixtures", "development rights", "construction"],
    },
}


# ---------------------------------------------------------------------------
# State Format Reference (for ingestion agent logic)
# ---------------------------------------------------------------------------
STATE_FORMATS = {
    "NY": {"format": "CSV", "delimiter": ",", "encoding": "utf-8", "date_format": "%Y-%m-%d",
           "filing_number_pattern": r"NY-\d{4}-\d{7}", "notes": "Standard CSV with headers"},
    "DE": {"format": "XML", "encoding": "utf-8", "date_format": "%Y-%m-%d",
           "filing_number_pattern": r"DE-\d{4}-\d{7}",
           "notes": "XML format with namespace declarations; Delaware always uses XML"},
    "CA": {"format": "CSV", "delimiter": ",", "encoding": "utf-8", "date_format": "%m/%d/%Y",
           "filing_number_pattern": r"CA-\d{4}-\d{7}", "notes": "CSV with MM/DD/YYYY dates"},
    "TX": {"format": "fixed_width", "encoding": "latin-1", "date_format": "%Y%m%d",
           "filing_number_pattern": r"TX-\d{4}-\d{7}",
           "notes": "Fixed-width format; dates without delimiters; latin-1 encoding"},
    "FL": {"format": "CSV", "delimiter": "|", "encoding": "utf-8", "date_format": "%Y-%m-%d",
           "filing_number_pattern": r"FL-\d{4}-\d{7}", "notes": "Pipe-delimited CSV"},
}


# ---------------------------------------------------------------------------
# Evaluation helpers — expected outputs for common queries
# ---------------------------------------------------------------------------
EXPECTED_OUTPUTS = {
    "acme_total_filings": 10,  # active filings across all states for Acme Corp / Acme Corporation
    "acme_total_secured_parties": 8,  # unique secured parties across Acme filings
    "pinnacle_systems_total_filings": 7,  # including name variations
    "trident_total_filings": 4,
    "lapsed_filing_count": 3,  # NY-2019-0892341, DE-2019-0042198, CA-2019-0398172
    "terminated_filing_count": 3,  # NY-2023-0781924, DE-2024-0045123, CA-2023-0678492
    "entities_with_name_changes": ["94-3829471", "95-7712034", "51-0482193", "13-9923847", "94-6653218"],
}
