-- =====================================================================
-- Sequences + BEFORE INSERT triggers -- the pre-12c identity pattern.
--
-- PostgreSQL translation: these five sequence/trigger PAIRS collapse
-- into `GENERATED BY DEFAULT AS IDENTITY` on the column, plus a
-- setval()-equivalent to set the high-water mark after the data load.
-- The trigger itself should NOT be emitted. A translator that faithfully
-- reproduces the trigger has misunderstood the intent.
-- =====================================================================

ALTER SESSION SET CURRENT_SCHEMA = MERIDIAN;

CREATE SEQUENCE seq_filing_id       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_debtor_id       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_secured_party_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_amendment_id    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_audit_id        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER trg_filing_bi
BEFORE INSERT ON ucc_filing
FOR EACH ROW
WHEN (NEW.filing_id IS NULL)
BEGIN
  :NEW.filing_id := seq_filing_id.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_debtor_bi
BEFORE INSERT ON ucc_debtor
FOR EACH ROW
WHEN (NEW.debtor_id IS NULL)
BEGIN
  :NEW.debtor_id := seq_debtor_id.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_secured_party_bi
BEFORE INSERT ON ucc_secured_party
FOR EACH ROW
WHEN (NEW.secured_party_id IS NULL)
BEGIN
  :NEW.secured_party_id := seq_secured_party_id.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_amendment_bi
BEFORE INSERT ON ucc_amendment
FOR EACH ROW
WHEN (NEW.amendment_id IS NULL)
BEGIN
  :NEW.amendment_id := seq_amendment_id.NEXTVAL;
END;
/

-- This one is NOT a pure identity trigger -- it also normalizes the name
-- and stamps a lapse date. Collapsing it to an identity column would
-- LOSE business logic. The translator must split it: identity for the
-- id, a separate PostgreSQL BEFORE INSERT trigger for the rest.
CREATE OR REPLACE TRIGGER trg_filing_normalize_bi
BEFORE INSERT ON ucc_filing
FOR EACH ROW
BEGIN
  :NEW.filing_number := UPPER(TRIM(:NEW.filing_number));
  IF :NEW.lapse_date IS NULL AND :NEW.filing_type = 'UCC1' THEN
    -- UCC-1 financing statements lapse 5 years after filing
    :NEW.lapse_date := ADD_MONTHS(:NEW.filed_date, 60);
  END IF;
END;
/
