-- =====================================================================
-- Seed data: 11 states, 5,000 filings, ~7,400 debtors, ~5,300 secured
-- parties, ~1,800 amendments (some nested 3 deep), 400 audit rows.
--
-- Generated by a PL/SQL loop rather than 5,000 literal INSERTs so the
-- container boots in seconds instead of minutes.
--
-- PLANTED DEFECTS -- these are the point of the lab:
--   1. ~1,400 ucc_debtor rows have mailing_address_2 = '' which Oracle
--      silently stores as NULL. A naive CSV round-trip turns these into
--      PostgreSQL empty strings.
--   2. Every filed_date carries a non-midnight TIME component, so
--      mapping Oracle DATE to PostgreSQL `date` loses data visibly.
--   3. One filing (number 'CA-2019-000042') has a lapse_date in the
--      past but status 'ACTIVE' -- referential-logic drift the
--      validator's spot check should surface.
-- =====================================================================

ALTER SESSION SET CURRENT_SCHEMA = MERIDIAN;

-- ---------------------------------------------------------------- states
INSERT INTO state_sos_source (state_code, state_name, feed_format, last_sync, records_expected, is_active) VALUES ('CA','California','PIPE_CSV',    SYSTIMESTAMP - 1, 812,  'Y');
INSERT INTO state_sos_source (state_code, state_name, feed_format, last_sync, records_expected, is_active) VALUES ('NY','New York',  'XML',         SYSTIMESTAMP - 2, 640,  'Y');
INSERT INTO state_sos_source (state_code, state_name, feed_format, last_sync, records_expected, is_active) VALUES ('TX','Texas',     'FIXED_WIDTH', SYSTIMESTAMP - 1, 733,  'Y');
INSERT INTO state_sos_source (state_code, state_name, feed_format, last_sync, records_expected, is_active) VALUES ('FL','Florida',   'JSON',        SYSTIMESTAMP - 3, 588,  'Y');
INSERT INTO state_sos_source (state_code, state_name, feed_format, last_sync, records_expected, is_active) VALUES ('IL','Illinois',  'XML',         SYSTIMESTAMP - 1, 421,  'Y');
INSERT INTO state_sos_source (state_code, state_name, feed_format, last_sync, records_expected, is_active) VALUES ('OH','Ohio',      'PIPE_CSV',    SYSTIMESTAMP - 4, 366,  'Y');
INSERT INTO state_sos_source (state_code, state_name, feed_format, last_sync, records_expected, is_active) VALUES ('PA','Pennsylvania','COMMA_CSV', SYSTIMESTAMP - 2, 351,  'Y');
INSERT INTO state_sos_source (state_code, state_name, feed_format, last_sync, records_expected, is_active) VALUES ('GA','Georgia',   'PIPE_CSV',    SYSTIMESTAMP - 5, 318,  'Y');
INSERT INTO state_sos_source (state_code, state_name, feed_format, last_sync, records_expected, is_active) VALUES ('WA','Washington','XML',         SYSTIMESTAMP - 1, 289,  'Y');
INSERT INTO state_sos_source (state_code, state_name, feed_format, last_sync, records_expected, is_active) VALUES ('CO','Colorado',  'PIPE_CSV',    SYSTIMESTAMP - 6, 264,  'Y');
INSERT INTO state_sos_source (state_code, state_name, feed_format, last_sync, records_expected, is_active) VALUES ('NV','Nevada',    'JSON',        NULL,             218,  'N');
COMMIT;

-- ------------------------------------------------------- filings + kids
DECLARE
  TYPE t_str_arr IS TABLE OF VARCHAR2(60);

  v_states    t_str_arr := t_str_arr('CA','NY','TX','FL','IL','OH','PA','GA','WA','CO','NV');
  v_types     t_str_arr := t_str_arr('UCC1','UCC1','UCC1','UCC1','UCC3_AMD','UCC3_CONT','UCC3_TERM','UCC5');
  v_orgs      t_str_arr := t_str_arr(
                 'ACME CORPORATION','PINNACLE INDUSTRIES LLC','NORTHWIND TRADING CO',
                 'BLUE RIDGE MANUFACTURING','SUMMIT LOGISTICS GROUP','CEDAR POINT HOLDINGS',
                 'IRONGATE CAPITAL PARTNERS','MERIDIAN FOODS INC','ATLAS FREIGHT SYSTEMS',
                 'HARBORVIEW PROPERTIES LP','QUANTUM TOOLING LLC','SILVERLAKE AGRONOMICS');
  v_banks     t_str_arr := t_str_arr(
                 'FIRST NATIONAL BANK','COMMERCE CREDIT UNION','WESTFIELD CAPITAL',
                 'BRIDGEPORT LENDING LLC','GRANITE EQUIPMENT FINANCE');
  v_collat    t_str_arr := t_str_arr(
                 'All assets of the debtor, whether now owned or hereafter acquired.',
                 'Specific equipment: 2019 CAT 336 excavator, serial CAT0336ELMS00921.',
                 'Accounts receivable and proceeds thereof.',
                 'Inventory located at 4400 Industrial Parkway.',
                 'All assets including general intangibles and fixtures.');

  v_state     VARCHAR2(2);
  v_type      VARCHAR2(12);
  v_filed     DATE;
  v_fid       NUMBER;
  v_did       NUMBER;
  v_amd_root  NUMBER;
  v_amd_mid   NUMBER;
  v_addr2     VARCHAR2(120);
BEGIN
  FOR i IN 1 .. 5000 LOOP
    v_state := v_states(MOD(i, v_states.COUNT) + 1);
    v_type  := v_types(MOD(i, v_types.COUNT) + 1);

    -- PLANTED DEFECT 2: every filed_date carries a real time component.
    -- Oracle DATE holds it; PostgreSQL `date` would silently drop it.
    v_filed := TO_DATE('2016-01-01','YYYY-MM-DD')
               + MOD(i * 7, 3200)
               + (MOD(i * 13, 86400) / 86400);

    v_fid := seq_filing_id.NEXTVAL;

    INSERT INTO ucc_filing (
      filing_id, filing_number, state_code, filing_type, filed_date,
      lapse_date, status, collateral_desc, page_count, filing_fee, created_by, created_ts)
    VALUES (
      v_fid,
      v_state || '-' || TO_CHAR(EXTRACT(YEAR FROM v_filed)) || '-' || LPAD(i, 6, '0'),
      v_state,
      v_type,
      v_filed,
      CASE WHEN v_type = 'UCC1' THEN ADD_MONTHS(v_filed, 60) ELSE NULL END,
      CASE MOD(i, 17)
        WHEN 0 THEN 'TERMINATED'
        WHEN 5 THEN 'LAPSED'
        ELSE 'ACTIVE'
      END,
      v_collat(MOD(i, v_collat.COUNT) + 1),
      MOD(i, 9) + 1,
      ROUND(25 + MOD(i * 3, 175) + 0.50, 2),
      'LEGACY_ETL',
      v_filed);

    -- ---- debtors: 1 or 2 per filing --------------------------------
    FOR d IN 1 .. (CASE WHEN MOD(i, 3) = 0 THEN 2 ELSE 1 END) LOOP
      -- PLANTED DEFECT 1: the empty-string trap.
      -- Oracle stores '' as NULL. Roughly 28% of rows get it.
      IF MOD(i + d, 7) < 2 THEN
        v_addr2 := '';                       -- <-- becomes NULL in Oracle
      ELSIF MOD(i + d, 7) = 3 THEN
        v_addr2 := NULL;                     -- explicitly NULL
      ELSE
        v_addr2 := 'Suite ' || TO_CHAR(MOD(i * d, 900) + 100);
      END IF;

      v_did := seq_debtor_id.NEXTVAL;
      INSERT INTO ucc_debtor (
        debtor_id, filing_id, debtor_name, debtor_type,
        mailing_address_1, mailing_address_2, city, state_code, postal_code)
      VALUES (
        v_did,
        v_fid,
        v_orgs(MOD(i + d, v_orgs.COUNT) + 1),
        CASE WHEN MOD(i, 11) = 0 THEN 'INDIVIDUAL' ELSE 'ORGANIZATION' END,
        TO_CHAR(MOD(i * 17, 8900) + 100) || ' Commerce Way',
        v_addr2,
        CASE MOD(i, 5)
          WHEN 0 THEN 'Springfield' WHEN 1 THEN 'Riverton'
          WHEN 2 THEN 'Fairview'    WHEN 3 THEN 'Georgetown'
          ELSE 'Clinton' END,
        v_state,
        LPAD(TO_CHAR(MOD(i * 31, 89999) + 10000), 5, '0'));
    END LOOP;

    -- ---- secured party --------------------------------------------
    INSERT INTO ucc_secured_party (
      secured_party_id, filing_id, party_name, tax_id, contact_email, is_assignee)
    VALUES (
      seq_secured_party_id.NEXTVAL,
      v_fid,
      v_banks(MOD(i, v_banks.COUNT) + 1),
      SYS_GUID(),                       -- RAW(16) -> uuid
      LOWER(REPLACE(v_banks(MOD(i, v_banks.COUNT) + 1), ' ', '.')) || '@example.com',
      CASE WHEN MOD(i, 23) = 0 THEN 'Y' ELSE 'N' END);

    -- ---- amendments: a 3-level chain every 12th filing -------------
    IF MOD(i, 12) = 0 THEN
      v_amd_root := seq_amendment_id.NEXTVAL;
      INSERT INTO ucc_amendment (amendment_id, filing_id, parent_amendment_id,
                                 amendment_type, amendment_date, notes)
      VALUES (v_amd_root, v_fid, NULL, 'AMENDMENT',
              v_filed + 120, 'Collateral description expanded');

      v_amd_mid := seq_amendment_id.NEXTVAL;
      INSERT INTO ucc_amendment (amendment_id, filing_id, parent_amendment_id,
                                 amendment_type, amendment_date, notes)
      VALUES (v_amd_mid, v_fid, v_amd_root, 'CONTINUATION',
              v_filed + 900, 'Five-year continuation filed');

      INSERT INTO ucc_amendment (amendment_id, filing_id, parent_amendment_id,
                                 amendment_type, amendment_date, notes)
      VALUES (seq_amendment_id.NEXTVAL, v_fid, v_amd_mid, 'ASSIGNMENT',
              v_filed + 1100, 'Assigned to successor secured party');
    END IF;

    IF MOD(i, 500) = 0 THEN
      COMMIT;
    END IF;
  END LOOP;

  COMMIT;
END;
/

-- PLANTED DEFECT 3: a filing that is ACTIVE but already past its lapse
-- date. Nothing in the schema forbids it; only a data-quality check
-- finds it. The validator's spot check should surface this.
UPDATE ucc_filing
   SET filing_number = 'CA-2019-000042',
       lapse_date    = TO_DATE('2021-06-30 09:15:00','YYYY-MM-DD HH24:MI:SS'),
       status        = 'ACTIVE'
 WHERE filing_id = (SELECT MIN(filing_id) FROM ucc_filing WHERE state_code = 'CA');
COMMIT;

-- ---------------------------------------------------------- audit rows
INSERT INTO filing_audit (audit_id, filing_id, action, detail)
SELECT seq_audit_id.NEXTVAL, filing_id, 'LOAD', 'Initial legacy load 2003 migration'
  FROM ucc_filing
 WHERE MOD(filing_id, 13) = 0;
COMMIT;

-- Build the materialized view now that data exists.
BEGIN
  DBMS_MVIEW.REFRESH('MV_STATE_ROLLUP', 'C');
END;
/

-- Gather stats so the agent's row-count estimates are realistic.
BEGIN
  DBMS_STATS.GATHER_SCHEMA_STATS('MERIDIAN');
END;
/

-- ------------------------------------------------------------------
-- Grant the read-only agent user SELECT on everything, now that the
-- objects exist. This is the second half of the defense-in-depth pair
-- started in 00_user.sql: the hook blocks writes in the agent, and
-- these grants mean the database would refuse them anyway.
-- ------------------------------------------------------------------
BEGIN
  FOR r IN (SELECT object_name, object_type
              FROM all_objects
             WHERE owner = 'MERIDIAN'
               AND object_type IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')) LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT ON meridian.' || r.object_name
                      || ' TO migration_reader';
  END LOOP;
END;
/
