"""
Mock data for B2B Ecommerce Order Exception Resolution Agent.

This module contains realistic (but fictional) order data, warehouse inventory,
carrier tracking, contract pricing, and quality hold information.
"""

# ---------------------------------------------------------------------------
# Orders Database
# ---------------------------------------------------------------------------
ORDERS = {
    "ORD-2024-1847": {
        "order_id": "ORD-2024-1847",
        "po_number": "PO-88421",
        "customer_id": "CUST-4420",
        "customer_name": "Meridian Industrial Supply",
        "order_date": "2024-11-15",
        "promised_delivery": "2024-11-22",
        "status": "exception",
        "exception_type": "delayed_shipment",
        "exception_details": "Carrier pickup missed — truck not dispatched due to routing error",
        "priority": "high",
        "total_value": 14750.00,
        "currency": "USD",
        "lines": [
            {
                "line": 1,
                "sku": "HYD-PUMP-3200",
                "description": "Hydraulic Pump Assembly 3200 PSI",
                "qty_ordered": 5,
                "qty_shipped": 0,
                "unit_price": 1850.00,
                "warehouse": "WH-EAST",
            },
            {
                "line": 2,
                "sku": "FLT-KIT-STD",
                "description": "Standard Filter Replacement Kit",
                "qty_ordered": 25,
                "qty_shipped": 0,
                "unit_price": 120.00,
                "warehouse": "WH-EAST",
            },
            {
                "line": 3,
                "sku": "SEAL-VIT-050",
                "description": "Viton O-Ring Seal Set 50mm",
                "qty_ordered": 100,
                "qty_shipped": 0,
                "unit_price": 8.50,
                "warehouse": "WH-EAST",
            },
        ],
        "shipping": {
            "carrier": "FastFreight Logistics",
            "carrier_code": "FFL",
            "service_level": "2-Day Priority",
            "tracking_number": "FFL-9928374650",
            "ship_from": "WH-EAST",
        },
        "contract_id": "CTR-2024-0091",
        "sla_penalty_clause": True,
        "sla_penalty_rate": 0.02,
        "contact_email": "procurement@meridian-industrial.com",
        "contact_name": "Janet Kowalski",
    },
    "ORD-2024-1852": {
        "order_id": "ORD-2024-1852",
        "po_number": "PO-88455",
        "customer_id": "CUST-3310",
        "customer_name": "TechBuild Components Inc",
        "order_date": "2024-11-16",
        "promised_delivery": "2024-11-25",
        "status": "exception",
        "exception_type": "partial_delivery",
        "exception_details": "Line 2 (PCB-CTRL-V4) short-shipped — only 30 of 50 units available at WH-WEST",
        "priority": "medium",
        "total_value": 23400.00,
        "currency": "USD",
        "lines": [
            {
                "line": 1,
                "sku": "MTR-SERVO-750",
                "description": "Servo Motor 750W with Encoder",
                "qty_ordered": 10,
                "qty_shipped": 10,
                "unit_price": 680.00,
                "warehouse": "WH-WEST",
            },
            {
                "line": 2,
                "sku": "PCB-CTRL-V4",
                "description": "Motion Controller PCB v4.2",
                "qty_ordered": 50,
                "qty_shipped": 30,
                "unit_price": 340.00,
                "warehouse": "WH-WEST",
            },
        ],
        "shipping": {
            "carrier": "National Freight Systems",
            "carrier_code": "NFS",
            "service_level": "Standard Ground",
            "tracking_number": "NFS-5501928374",
            "ship_from": "WH-WEST",
        },
        "contract_id": "CTR-2024-0078",
        "sla_penalty_clause": False,
        "contact_email": "orders@techbuild.com",
        "contact_name": "Mike Tran",
    },
    "ORD-2024-1860": {
        "order_id": "ORD-2024-1860",
        "po_number": "PO-88490",
        "customer_id": "CUST-5510",
        "customer_name": "Greenfield Energy Solutions",
        "order_date": "2024-11-17",
        "promised_delivery": "2024-11-24",
        "status": "exception",
        "exception_type": "pricing_discrepancy",
        "exception_details": "Customer contract price $42.00/unit for CABLE-SOL-10AWG but system charged $55.00/unit (list price)",
        "priority": "medium",
        "total_value": 11750.00,
        "currency": "USD",
        "lines": [
            {
                "line": 1,
                "sku": "CABLE-SOL-10AWG",
                "description": "Solar Cable 10AWG UV-Resistant 500ft",
                "qty_ordered": 200,
                "qty_shipped": 200,
                "unit_price": 55.00,
                "warehouse": "WH-CENTRAL",
            },
            {
                "line": 2,
                "sku": "CONN-MC4-SET",
                "description": "MC4 Connector Pair Set",
                "qty_ordered": 50,
                "qty_shipped": 50,
                "unit_price": 7.50,
                "warehouse": "WH-CENTRAL",
            },
        ],
        "shipping": {
            "carrier": "FastFreight Logistics",
            "carrier_code": "FFL",
            "service_level": "Standard Ground",
            "tracking_number": "FFL-9930128456",
            "ship_from": "WH-CENTRAL",
        },
        "contract_id": "CTR-2023-0155",
        "sla_penalty_clause": False,
        "contact_email": "ap@greenfieldenergy.com",
        "contact_name": "Sandra Liu",
    },
    "ORD-2024-1873": {
        "order_id": "ORD-2024-1873",
        "po_number": "PO-88512",
        "customer_id": "CUST-2280",
        "customer_name": "Atlas Manufacturing Group",
        "order_date": "2024-11-18",
        "promised_delivery": "2024-11-22",
        "status": "exception",
        "exception_type": "quality_hold",
        "exception_details": "Lot BATCH-2024-1109 of BEAR-LIN-25MM flagged for dimensional variance — QC hold pending inspection",
        "priority": "high",
        "total_value": 8200.00,
        "currency": "USD",
        "lines": [
            {
                "line": 1,
                "sku": "BEAR-LIN-25MM",
                "description": "Linear Bearing 25mm Precision Grade",
                "qty_ordered": 40,
                "qty_shipped": 0,
                "unit_price": 145.00,
                "warehouse": "WH-EAST",
            },
            {
                "line": 2,
                "sku": "RAIL-LIN-500",
                "description": "Linear Guide Rail 500mm",
                "qty_ordered": 20,
                "qty_shipped": 0,
                "unit_price": 120.00,
                "warehouse": "WH-EAST",
            },
        ],
        "shipping": {
            "carrier": "National Freight Systems",
            "carrier_code": "NFS",
            "service_level": "2-Day Priority",
            "tracking_number": None,
            "ship_from": "WH-EAST",
        },
        "contract_id": "CTR-2024-0102",
        "sla_penalty_clause": True,
        "sla_penalty_rate": 0.015,
        "contact_email": "purchasing@atlasmfg.com",
        "contact_name": "Carlos Rivera",
    },
    "ORD-2024-1880": {
        "order_id": "ORD-2024-1880",
        "po_number": "PO-88530",
        "customer_id": "CUST-6650",
        "customer_name": "Northstar Robotics Ltd",
        "order_date": "2024-11-19",
        "promised_delivery": "2024-11-26",
        "status": "exception",
        "exception_type": "delayed_shipment",
        "exception_details": "Carrier service disruption — NFS regional hub closed due to severe weather in Midwest",
        "priority": "medium",
        "total_value": 32100.00,
        "currency": "USD",
        "lines": [
            {
                "line": 1,
                "sku": "ACT-LIN-200N",
                "description": "Linear Actuator 200N 300mm Stroke",
                "qty_ordered": 15,
                "qty_shipped": 0,
                "unit_price": 890.00,
                "warehouse": "WH-CENTRAL",
            },
            {
                "line": 2,
                "sku": "DRV-STEP-NEMA34",
                "description": "NEMA 34 Stepper Driver with Microstep",
                "qty_ordered": 15,
                "qty_shipped": 0,
                "unit_price": 420.00,
                "warehouse": "WH-CENTRAL",
            },
            {
                "line": 3,
                "sku": "ENC-ABS-4096",
                "description": "Absolute Encoder 4096 PPR",
                "qty_ordered": 30,
                "qty_shipped": 0,
                "unit_price": 215.00,
                "warehouse": "WH-CENTRAL",
            },
        ],
        "shipping": {
            "carrier": "National Freight Systems",
            "carrier_code": "NFS",
            "service_level": "Standard Ground",
            "tracking_number": "NFS-5503847291",
            "ship_from": "WH-CENTRAL",
        },
        "contract_id": "CTR-2024-0118",
        "sla_penalty_clause": False,
        "contact_email": "logistics@northstarrobotics.com",
        "contact_name": "Erin Nakamura",
    },
    "ORD-2024-1891": {
        "order_id": "ORD-2024-1891",
        "po_number": "PO-88548",
        "customer_id": "CUST-7710",
        "customer_name": "Summit Aerospace Components",
        "order_date": "2024-11-20",
        "promised_delivery": "2024-11-27",
        "status": "exception",
        "exception_type": "partial_delivery",
        "exception_details": "SKU FSTNR-TI-M6 discontinued — last batch shipped, remaining qty unavailable",
        "priority": "high",
        "total_value": 19500.00,
        "currency": "USD",
        "lines": [
            {
                "line": 1,
                "sku": "FSTNR-TI-M6",
                "description": "Titanium Fastener M6x25 Grade 5 (Discontinued)",
                "qty_ordered": 500,
                "qty_shipped": 180,
                "unit_price": 3.20,
                "warehouse": "WH-EAST",
            },
            {
                "line": 2,
                "sku": "WSHR-TI-M6",
                "description": "Titanium Washer M6 Grade 5",
                "qty_ordered": 500,
                "qty_shipped": 500,
                "unit_price": 1.50,
                "warehouse": "WH-EAST",
            },
            {
                "line": 3,
                "sku": "BRKT-AL-7075",
                "description": "7075 Aluminum Mounting Bracket",
                "qty_ordered": 50,
                "qty_shipped": 50,
                "unit_price": 340.00,
                "warehouse": "WH-EAST",
            },
        ],
        "shipping": {
            "carrier": "FastFreight Logistics",
            "carrier_code": "FFL",
            "service_level": "Next Day Air",
            "tracking_number": "FFL-9931557823",
            "ship_from": "WH-EAST",
        },
        "contract_id": "CTR-2024-0065",
        "sla_penalty_clause": True,
        "sla_penalty_rate": 0.025,
        "contact_email": "procurement@summitaero.com",
        "contact_name": "Daniel Hawthorne",
    },
    "ORD-2024-1903": {
        "order_id": "ORD-2024-1903",
        "po_number": "PO-88570",
        "customer_id": "CUST-8820",
        "customer_name": "Cascade Water Systems",
        "order_date": "2024-11-21",
        "promised_delivery": "2024-11-28",
        "status": "exception",
        "exception_type": "pricing_discrepancy",
        "exception_details": "Contract CTR-2023-0200 expired 2024-10-31. Customer claims renewal was submitted. System applied list pricing.",
        "priority": "low",
        "total_value": 6800.00,
        "currency": "USD",
        "lines": [
            {
                "line": 1,
                "sku": "VLV-GATE-4IN",
                "description": "Gate Valve 4-inch Brass",
                "qty_ordered": 20,
                "qty_shipped": 20,
                "unit_price": 340.00,
                "warehouse": "WH-WEST",
            },
        ],
        "shipping": {
            "carrier": "Regional Express",
            "carrier_code": "REX",
            "service_level": "Standard Ground",
            "tracking_number": "REX-7720019384",
            "ship_from": "WH-WEST",
        },
        "contract_id": "CTR-2023-0200",
        "sla_penalty_clause": False,
        "contact_email": "billing@cascadewater.com",
        "contact_name": "Patricia Dunn",
    },
    "ORD-2024-1910": {
        "order_id": "ORD-2024-1910",
        "po_number": "PO-88595",
        "customer_id": "CUST-4420",
        "customer_name": "Meridian Industrial Supply",
        "order_date": "2024-11-22",
        "promised_delivery": "2024-11-29",
        "status": "exception",
        "exception_type": "quality_hold",
        "exception_details": "Customer-reported defect on prior order — hold all HYD-PUMP-3200 shipments pending supplier investigation",
        "priority": "critical",
        "total_value": 37000.00,
        "currency": "USD",
        "lines": [
            {
                "line": 1,
                "sku": "HYD-PUMP-3200",
                "description": "Hydraulic Pump Assembly 3200 PSI",
                "qty_ordered": 20,
                "qty_shipped": 0,
                "unit_price": 1850.00,
                "warehouse": "WH-EAST",
            },
        ],
        "shipping": {
            "carrier": "FastFreight Logistics",
            "carrier_code": "FFL",
            "service_level": "2-Day Priority",
            "tracking_number": None,
            "ship_from": "WH-EAST",
        },
        "contract_id": "CTR-2024-0091",
        "sla_penalty_clause": True,
        "sla_penalty_rate": 0.02,
        "contact_email": "procurement@meridian-industrial.com",
        "contact_name": "Janet Kowalski",
    },
}

# ---------------------------------------------------------------------------
# Warehouse Inventory
# ---------------------------------------------------------------------------
WAREHOUSE_INVENTORY = {
    "WH-EAST": {
        "warehouse_id": "WH-EAST",
        "name": "Eastern Distribution Center",
        "location": "Edison, NJ",
        "inventory": {
            "HYD-PUMP-3200": {"qty_available": 12, "qty_reserved": 5, "qty_on_hold": 20, "reorder_point": 10, "lead_time_days": 21, "lot_number": "BATCH-2024-1105"},
            "FLT-KIT-STD": {"qty_available": 340, "qty_reserved": 25, "qty_on_hold": 0, "reorder_point": 50, "lead_time_days": 7},
            "SEAL-VIT-050": {"qty_available": 1200, "qty_reserved": 100, "qty_on_hold": 0, "reorder_point": 200, "lead_time_days": 5},
            "BEAR-LIN-25MM": {"qty_available": 0, "qty_reserved": 0, "qty_on_hold": 40, "reorder_point": 20, "lead_time_days": 14, "lot_number": "BATCH-2024-1109", "hold_reason": "QC dimensional variance inspection"},
            "RAIL-LIN-500": {"qty_available": 55, "qty_reserved": 20, "qty_on_hold": 0, "reorder_point": 15, "lead_time_days": 14},
            "FSTNR-TI-M6": {"qty_available": 0, "qty_reserved": 0, "qty_on_hold": 0, "reorder_point": 0, "lead_time_days": None, "status": "DISCONTINUED", "last_batch_shipped": 180, "replacement_sku": "FSTNR-TI-M6-V2"},
            "WSHR-TI-M6": {"qty_available": 2400, "qty_reserved": 0, "qty_on_hold": 0, "reorder_point": 500, "lead_time_days": 10},
            "BRKT-AL-7075": {"qty_available": 120, "qty_reserved": 50, "qty_on_hold": 0, "reorder_point": 25, "lead_time_days": 18},
        },
    },
    "WH-WEST": {
        "warehouse_id": "WH-WEST",
        "name": "Western Distribution Center",
        "location": "Ontario, CA",
        "inventory": {
            "MTR-SERVO-750": {"qty_available": 45, "qty_reserved": 0, "qty_on_hold": 0, "reorder_point": 15, "lead_time_days": 28},
            "PCB-CTRL-V4": {"qty_available": 18, "qty_reserved": 0, "qty_on_hold": 0, "reorder_point": 30, "lead_time_days": 35, "next_replenishment": "2024-12-15"},
            "VLV-GATE-4IN": {"qty_available": 80, "qty_reserved": 0, "qty_on_hold": 0, "reorder_point": 20, "lead_time_days": 12},
        },
    },
    "WH-CENTRAL": {
        "warehouse_id": "WH-CENTRAL",
        "name": "Central Distribution Hub",
        "location": "Dallas, TX",
        "inventory": {
            "CABLE-SOL-10AWG": {"qty_available": 600, "qty_reserved": 0, "qty_on_hold": 0, "reorder_point": 100, "lead_time_days": 10},
            "CONN-MC4-SET": {"qty_available": 450, "qty_reserved": 0, "qty_on_hold": 0, "reorder_point": 100, "lead_time_days": 7},
            "ACT-LIN-200N": {"qty_available": 22, "qty_reserved": 15, "qty_on_hold": 0, "reorder_point": 10, "lead_time_days": 21},
            "DRV-STEP-NEMA34": {"qty_available": 30, "qty_reserved": 15, "qty_on_hold": 0, "reorder_point": 10, "lead_time_days": 18},
            "ENC-ABS-4096": {"qty_available": 65, "qty_reserved": 30, "qty_on_hold": 0, "reorder_point": 20, "lead_time_days": 14},
        },
    },
}

# ---------------------------------------------------------------------------
# Carrier Tracking Data
# ---------------------------------------------------------------------------
CARRIER_TRACKING = {
    "FFL-9928374650": {
        "tracking_number": "FFL-9928374650",
        "carrier": "FastFreight Logistics",
        "status": "pickup_missed",
        "status_detail": "Pickup scheduled for 2024-11-18 was not completed. Routing error — truck dispatched to wrong facility.",
        "estimated_delivery": None,
        "origin": "WH-EAST (Edison, NJ)",
        "destination": "Meridian Industrial Supply, Cincinnati, OH",
        "events": [
            {"timestamp": "2024-11-15T14:30:00Z", "event": "Shipment created", "location": "Edison, NJ"},
            {"timestamp": "2024-11-18T06:00:00Z", "event": "Pickup scheduled", "location": "Edison, NJ"},
            {"timestamp": "2024-11-18T18:00:00Z", "event": "Pickup missed — routing error", "location": "Edison, NJ"},
        ],
        "service_disruption": False,
    },
    "NFS-5501928374": {
        "tracking_number": "NFS-5501928374",
        "carrier": "National Freight Systems",
        "status": "in_transit",
        "status_detail": "Partial shipment in transit. 10x MTR-SERVO-750 and 30x PCB-CTRL-V4 loaded.",
        "estimated_delivery": "2024-11-25",
        "origin": "WH-WEST (Ontario, CA)",
        "destination": "TechBuild Components Inc, Portland, OR",
        "events": [
            {"timestamp": "2024-11-18T10:00:00Z", "event": "Shipment created (partial)", "location": "Ontario, CA"},
            {"timestamp": "2024-11-18T16:00:00Z", "event": "Picked up by carrier", "location": "Ontario, CA"},
            {"timestamp": "2024-11-19T08:00:00Z", "event": "Departed facility", "location": "Fresno, CA"},
            {"timestamp": "2024-11-20T11:00:00Z", "event": "In transit", "location": "Medford, OR"},
        ],
        "service_disruption": False,
    },
    "FFL-9930128456": {
        "tracking_number": "FFL-9930128456",
        "carrier": "FastFreight Logistics",
        "status": "delivered",
        "status_detail": "Delivered to dock — signed by R. Fernandez",
        "estimated_delivery": "2024-11-22",
        "actual_delivery": "2024-11-22T10:45:00Z",
        "origin": "WH-CENTRAL (Dallas, TX)",
        "destination": "Greenfield Energy Solutions, Austin, TX",
        "events": [
            {"timestamp": "2024-11-19T08:00:00Z", "event": "Shipment created", "location": "Dallas, TX"},
            {"timestamp": "2024-11-19T14:00:00Z", "event": "Picked up", "location": "Dallas, TX"},
            {"timestamp": "2024-11-22T10:45:00Z", "event": "Delivered — signed by R. Fernandez", "location": "Austin, TX"},
        ],
        "service_disruption": False,
    },
    "NFS-5503847291": {
        "tracking_number": "NFS-5503847291",
        "carrier": "National Freight Systems",
        "status": "delayed",
        "status_detail": "Service disruption — regional hub (Kansas City) closed due to severe winter storm. Estimated 3-5 day delay.",
        "estimated_delivery": "2024-12-01",
        "original_estimated_delivery": "2024-11-26",
        "origin": "WH-CENTRAL (Dallas, TX)",
        "destination": "Northstar Robotics Ltd, Minneapolis, MN",
        "events": [
            {"timestamp": "2024-11-20T09:00:00Z", "event": "Shipment created", "location": "Dallas, TX"},
            {"timestamp": "2024-11-20T15:00:00Z", "event": "Picked up", "location": "Dallas, TX"},
            {"timestamp": "2024-11-21T12:00:00Z", "event": "Arrived at hub", "location": "Oklahoma City, OK"},
            {"timestamp": "2024-11-22T08:00:00Z", "event": "SERVICE ALERT: Hub closure — severe weather", "location": "Kansas City, MO"},
        ],
        "service_disruption": True,
        "disruption_reason": "Severe winter storm — Kansas City regional hub closed",
        "disruption_estimated_resolution": "2024-11-25",
    },
    "FFL-9931557823": {
        "tracking_number": "FFL-9931557823",
        "carrier": "FastFreight Logistics",
        "status": "in_transit",
        "status_detail": "Partial shipment — 180x FSTNR-TI-M6, 500x WSHR-TI-M6, 50x BRKT-AL-7075",
        "estimated_delivery": "2024-11-23",
        "origin": "WH-EAST (Edison, NJ)",
        "destination": "Summit Aerospace Components, Wichita, KS",
        "events": [
            {"timestamp": "2024-11-21T07:00:00Z", "event": "Shipment created (partial)", "location": "Edison, NJ"},
            {"timestamp": "2024-11-21T12:00:00Z", "event": "Picked up", "location": "Edison, NJ"},
            {"timestamp": "2024-11-22T06:00:00Z", "event": "In transit", "location": "Columbus, OH"},
        ],
        "service_disruption": False,
    },
    "REX-7720019384": {
        "tracking_number": "REX-7720019384",
        "carrier": "Regional Express",
        "status": "delivered",
        "status_detail": "Delivered — left at receiving dock",
        "estimated_delivery": "2024-11-27",
        "actual_delivery": "2024-11-26T14:20:00Z",
        "origin": "WH-WEST (Ontario, CA)",
        "destination": "Cascade Water Systems, Sacramento, CA",
        "events": [
            {"timestamp": "2024-11-22T10:00:00Z", "event": "Shipment created", "location": "Ontario, CA"},
            {"timestamp": "2024-11-22T16:00:00Z", "event": "Picked up", "location": "Ontario, CA"},
            {"timestamp": "2024-11-26T14:20:00Z", "event": "Delivered", "location": "Sacramento, CA"},
        ],
        "service_disruption": False,
    },
}

# ---------------------------------------------------------------------------
# Contract Pricing
# ---------------------------------------------------------------------------
CONTRACT_PRICING = {
    "CTR-2024-0091": {
        "contract_id": "CTR-2024-0091",
        "customer_id": "CUST-4420",
        "customer_name": "Meridian Industrial Supply",
        "effective_date": "2024-01-01",
        "expiration_date": "2024-12-31",
        "status": "active",
        "pricing_tiers": {
            "HYD-PUMP-3200": {"contract_price": 1750.00, "list_price": 1850.00, "min_qty": 5, "tier_discount": "5.4%"},
            "FLT-KIT-STD": {"contract_price": 105.00, "list_price": 120.00, "min_qty": 20, "tier_discount": "12.5%"},
            "SEAL-VIT-050": {"contract_price": 7.25, "list_price": 8.50, "min_qty": 50, "tier_discount": "14.7%"},
        },
        "volume_rebate": {"threshold": 100000, "rebate_pct": 0.02, "ytd_spend": 87500},
    },
    "CTR-2024-0078": {
        "contract_id": "CTR-2024-0078",
        "customer_id": "CUST-3310",
        "customer_name": "TechBuild Components Inc",
        "effective_date": "2024-03-01",
        "expiration_date": "2025-02-28",
        "status": "active",
        "pricing_tiers": {
            "MTR-SERVO-750": {"contract_price": 650.00, "list_price": 680.00, "min_qty": 5, "tier_discount": "4.4%"},
            "PCB-CTRL-V4": {"contract_price": 310.00, "list_price": 340.00, "min_qty": 25, "tier_discount": "8.8%"},
        },
        "volume_rebate": None,
    },
    "CTR-2023-0155": {
        "contract_id": "CTR-2023-0155",
        "customer_id": "CUST-5510",
        "customer_name": "Greenfield Energy Solutions",
        "effective_date": "2023-06-01",
        "expiration_date": "2025-05-31",
        "status": "active",
        "pricing_tiers": {
            "CABLE-SOL-10AWG": {"contract_price": 42.00, "list_price": 55.00, "min_qty": 100, "tier_discount": "23.6%"},
            "CONN-MC4-SET": {"contract_price": 6.50, "list_price": 7.50, "min_qty": 25, "tier_discount": "13.3%"},
        },
        "volume_rebate": {"threshold": 50000, "rebate_pct": 0.015, "ytd_spend": 62000},
    },
    "CTR-2024-0102": {
        "contract_id": "CTR-2024-0102",
        "customer_id": "CUST-2280",
        "customer_name": "Atlas Manufacturing Group",
        "effective_date": "2024-04-01",
        "expiration_date": "2025-03-31",
        "status": "active",
        "pricing_tiers": {
            "BEAR-LIN-25MM": {"contract_price": 130.00, "list_price": 145.00, "min_qty": 10, "tier_discount": "10.3%"},
            "RAIL-LIN-500": {"contract_price": 108.00, "list_price": 120.00, "min_qty": 10, "tier_discount": "10.0%"},
        },
        "volume_rebate": None,
    },
    "CTR-2024-0065": {
        "contract_id": "CTR-2024-0065",
        "customer_id": "CUST-7710",
        "customer_name": "Summit Aerospace Components",
        "effective_date": "2024-02-01",
        "expiration_date": "2025-01-31",
        "status": "active",
        "pricing_tiers": {
            "FSTNR-TI-M6": {"contract_price": 2.80, "list_price": 3.20, "min_qty": 100, "tier_discount": "12.5%"},
            "WSHR-TI-M6": {"contract_price": 1.25, "list_price": 1.50, "min_qty": 100, "tier_discount": "16.7%"},
            "BRKT-AL-7075": {"contract_price": 315.00, "list_price": 340.00, "min_qty": 10, "tier_discount": "7.4%"},
        },
        "volume_rebate": {"threshold": 75000, "rebate_pct": 0.02, "ytd_spend": 71200},
    },
    "CTR-2023-0200": {
        "contract_id": "CTR-2023-0200",
        "customer_id": "CUST-8820",
        "customer_name": "Cascade Water Systems",
        "effective_date": "2023-11-01",
        "expiration_date": "2024-10-31",
        "status": "expired",
        "pricing_tiers": {
            "VLV-GATE-4IN": {"contract_price": 290.00, "list_price": 340.00, "min_qty": 10, "tier_discount": "14.7%"},
        },
        "volume_rebate": None,
        "renewal_status": "pending_review",
        "renewal_notes": "Customer submitted renewal request 2024-10-15. Sales team has not processed. Escalate to regional sales manager.",
    },
    "CTR-2024-0118": {
        "contract_id": "CTR-2024-0118",
        "customer_id": "CUST-6650",
        "customer_name": "Northstar Robotics Ltd",
        "effective_date": "2024-05-01",
        "expiration_date": "2025-04-30",
        "status": "active",
        "pricing_tiers": {
            "ACT-LIN-200N": {"contract_price": 820.00, "list_price": 890.00, "min_qty": 5, "tier_discount": "7.9%"},
            "DRV-STEP-NEMA34": {"contract_price": 385.00, "list_price": 420.00, "min_qty": 5, "tier_discount": "8.3%"},
            "ENC-ABS-4096": {"contract_price": 195.00, "list_price": 215.00, "min_qty": 10, "tier_discount": "9.3%"},
        },
        "volume_rebate": None,
    },
}

# ---------------------------------------------------------------------------
# Quality Hold Status
# ---------------------------------------------------------------------------
QUALITY_HOLDS = {
    "QH-2024-0447": {
        "hold_id": "QH-2024-0447",
        "sku": "BEAR-LIN-25MM",
        "lot_number": "BATCH-2024-1109",
        "warehouse": "WH-EAST",
        "hold_date": "2024-11-17",
        "hold_reason": "Dimensional variance detected during receiving inspection — outer diameter 25.08mm vs spec 25.00mm +/- 0.02mm",
        "severity": "critical",
        "qty_on_hold": 40,
        "inspection_status": "pending",
        "inspector": "QC-Team-East",
        "estimated_resolution": "2024-11-24",
        "affected_orders": ["ORD-2024-1873"],
        "supplier": "Precision Bearings GmbH",
        "supplier_notified": True,
        "disposition_options": ["return_to_supplier", "sort_and_use_conforming", "scrap"],
        "notes": "Supplier investigating root cause. May be related to tooling wear on production line 4.",
    },
    "QH-2024-0451": {
        "hold_id": "QH-2024-0451",
        "sku": "HYD-PUMP-3200",
        "lot_number": "BATCH-2024-1105",
        "warehouse": "WH-EAST",
        "hold_date": "2024-11-20",
        "hold_reason": "Customer-reported field failure — seal leak under sustained 3000+ PSI operation. Investigation initiated.",
        "severity": "critical",
        "qty_on_hold": 20,
        "inspection_status": "investigation_in_progress",
        "inspector": "QC-Team-East + Supplier Engineering",
        "estimated_resolution": "2024-12-05",
        "affected_orders": ["ORD-2024-1910"],
        "supplier": "HydroForce Manufacturing",
        "supplier_notified": True,
        "disposition_options": ["full_recall", "enhanced_testing_and_release", "design_revision"],
        "notes": "Field failure reported by Meridian Industrial Supply on prior shipment. All HYD-PUMP-3200 units from BATCH-2024-1105 quarantined pending root cause analysis. Supplier engineering on-site 2024-11-25.",
    },
}
